import assert from 'node:assert/strict';
import {NotebookStore,PROPERTY,BACKUP,decode,searchRecipes} from './core.js';
let checks=0;const check=(name,fn)=>{fn();checks++;console.log('PASS '+name);};
const mock=()=>{const m=new Map();return {m,getDynamicProperty:k=>m.get(k),setDynamicProperty:(k,v)=>m.set(k,v)};};
const a=mock(),b=mock(),sa=new NotebookStore(a),sb=new NotebookStore(b);
const recipe={name:'牛肉與辣椒',ingredients:[{item:'minecraft:beef'},{item:'kaleidoscope_cookery:red_chili'}],note:'材料次序保留',state:'raw'};
check('empty',()=>assert.equal(sa.read().recipes.length,0));
check('save',()=>assert.equal(sa.save(recipe).result,1));
check('player isolation',()=>assert.equal(sb.read().recipes.length,0));
check('new instance reload',()=>assert.equal(new NotebookStore(a).read().recipes[0].name,recipe.name));
check('ordered ingredients',()=>assert.deepEqual(sa.read().recipes[0].ingredients.map(x=>x.item),['minecraft:beef','kaleidoscope_cookery:red_chili']));
check('favorite',()=>sa.favorite('kaleidoscope_grilling:raw_beef_skewer',true));
check('favorite idempotent',()=>{sa.favorite('kaleidoscope_grilling:raw_beef_skewer',true);assert.equal(sa.read().favorites.length,1);});
check('stale conflict',()=>assert.throws(()=>sa.save(recipe,1,0),e=>e.code==='STALE'));
check('edit',()=>{sa.save({...recipe,name:'改名'},1,sa.read().revision);assert.equal(sa.read().recipes[0].name,'改名');});
check('invalid name rejected',()=>assert.throws(()=>sa.save({...recipe,name:'§khidden'})));
check('invalid identifier',()=>assert.throws(()=>sa.save({...recipe,ingredients:[{item:'x; kill @a'}]})));
check('no ingredients',()=>assert.throws(()=>sa.save({...recipe,ingredients:[]})));
check('too many ingredients',()=>assert.throws(()=>sa.save({...recipe,ingredients:Array(4).fill({item:'minecraft:beef'})})));
check('count validation',()=>assert.throws(()=>sa.save({...recipe,ingredients:[{item:'minecraft:beef',count:-1}]})));
check('corrupt preserved',()=>{const p=mock();p.m.set(PROPERTY,'bad');assert.throws(()=>new NotebookStore(p).save(recipe));assert.equal(p.m.get(PROPERTY),'bad');});
check('future schema preserved',()=>{const p=mock();p.m.set(PROPERTY,'{"schema":2}');assert.throws(()=>new NotebookStore(p).save(recipe));assert.equal(p.m.get(PROPERTY),'{"schema":2}');});
check('round trip',()=>assert.deepEqual(decode(sa.export()),sa.read()));
check('unicode search',()=>assert.equal(searchRecipes([{...recipe,id:'kg_a1:test'}],'牛肉').length,1));
check('ingredient search',()=>assert.equal(searchRecipes([{...recipe,id:'kg_a1:test'}],'minecraft:beef').length,1));
check('multi token search',()=>assert.equal(searchRecipes([{...recipe,id:'kg_a1:test'}],'牛肉 red_chili').length,1));
check('no result',()=>assert.equal(searchRecipes([{...recipe,id:'kg_a1:test'}],'missing').length,0));
check('remove',()=>{sa.remove(1,sa.read().revision);assert.equal(sa.read().recipes.length,0);});
check('backup',()=>assert.equal(decode(a.m.get(BACKUP)).recipes.length,1));
check('restore backup',()=>{sa.restoreBackup(sa.read().revision);assert.equal(sa.read().recipes.length,1);});
check('recipe IDs not reused',()=>assert.equal(sa.save(recipe).result,2));
check('missing edit',()=>assert.throws(()=>sa.save(recipe,1000)));
check('favorite remove',()=>{sa.favorite('kaleidoscope_grilling:raw_beef_skewer',false);assert.equal(sa.read().favorites.length,0);});
console.log(JSON.stringify({passed:checks,failed:0,scope:'storage logic with mock per-player adapter; not Minecraft persistence'}));
