// Executes reviewed author registry/board bodies with storage-operation doubles.
// No Minecraft player, author script or world is bundled with this test.
import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import crypto from 'node:crypto';import path from 'node:path';
import * as api from '../../projects/grilling/gameplay_core/behavior_pack/scripts/host_api/board_api_core.js';
import {BOARD_V2_RECIPES} from '../../projects/grilling/gameplay_core/behavior_pack/scripts/a2727_cookery_host_recipes_core.js';
const host=path.resolve(process.argv[2]),report=process.argv[3];if(!report)throw Error('Usage: <reviewed-extended-host> <report.json>');
const read=p=>fs.readFileSync(path.join(host,p),'utf8'),spec=JSON.parse(fs.readFileSync('projects/grilling/gameplay_core/behavior_pack/host-extensions/board-api.json'));
for(const [p,h] of Object.entries(spec.patched_files))assert.equal(crypto.createHash('sha256').update(read(p)).digest('hex'),h);
function fn(s,n){const start=s.indexOf('function '+n+'(');assert.ok(start>=0,n);let end=s.indexOf('{',start)+1,depth=1;while(depth){const c=s[end++];if(c==='{')depth++;if(c==='}')depth--}return s.slice(start,end)}
class Item{constructor(id,n=1){this.typeId=id;this.amount=n;this.maxAmount=id.includes('knife')?1:64;this.nameTag='';this.keepOnDeath=false;this.lockMode='none';this.damage=0}clone(){return Object.assign(new Item(this.typeId,this.amount),structuredClone({...this}))}getRawLore(){return this.lore??[]}setLore(v){this.lore=v}getCanDestroy(){return []}getCanPlaceOn(){return []}setCanDestroy(){}setCanPlaceOn(){}getDynamicPropertyIds(){return []}getComponent(k){if(k==='minecraft:durability'&&this.typeId.includes('knife')){const s=this;return {get damage(){return s.damage},set damage(v){s.damage=v},maxDurability:100,getDamageChance(){return 100}}}}}
let state={},hand,drops=[];const props=new Map(),equipment={hasItem:()=>!!hand,getItem:()=>hand?.clone(),setItem:s=>hand=s?.clone()};
const context=vm.createContext({...api,console,world:{getDynamicProperty:k=>props.get(k),setDynamicProperty:(k,v)=>v===undefined?props.delete(k):props.set(k,v)},system:{currentTick:0,afterEvents:{scriptEventReceive:{subscribe(){}}},run(){},runTimeout(){},runInterval(){},clearRun(){},sendScriptEvent(){}},ItemStack:Item,ItemTypes:{get:id=>({id})},GameMode:{Creative:'creative'}});
vm.runInContext(read('scripts/api/board_api_runtime.js').replace(/^import .*;\s*$/gm,'').replace(/^export \{.*\};\s*$/gm,'').replace(/\bexport /g,''),context);
vm.runInContext(read('scripts/data/stationRecipes.js').replace(/\bexport /g,''),context);vm.runInContext(read('scripts/data/stockpotJavaRecipes.js').replace(/\bexport /g,''),context);
vm.runInContext(read('scripts/api/extensionRegistry.js').replace(/^import\b[\s\S]*?;\s*/gm,'').replace(/\bexport /g,''),context);
for(const payload of BOARD_V2_RECIPES)assert.equal(vm.runInContext('registerExtensionRecipe',context)(payload).ok,true);
Object.assign(context,{held:()=>hand,slot:()=>equipment,load:()=>structuredClone(state),save:(b,s)=>{state=structuredClone(s);context.world.setDynamicProperty('station',Object.keys(s).length?JSON.stringify(s):undefined)},k:()=> 'station',isKitchenKnife:s=>s?.typeId==='qa:knife',emitBoardCutParticles(){},playSoundAccessible(){},msg(){},clearBoardExtension(){},clearDisplays(){}});
const station=read('scripts/custom_components/blocks/directStation.js');vm.runInContext(fn(station,'boardApiHost')+'\n'+fn(station,'boardInteract')+'\n'+fn(station,'spillDirectStationContents'),context);
const dimension={id:'overworld',spawnItem(stack){const e={isValid:true,getComponent:()=>({itemStack:stack}),remove(){this.isValid=false;drops.splice(drops.indexOf(this),1)}};drops.push(e);return e}},block={x:0,y:80,z:0,dimension},actor={getGameMode:()=> 'survival',isSneaking:false};
const run=()=>vm.runInContext('boardInteract',context)(block,actor);
let cases=[];
for(const payload of BOARD_V2_RECIPES){state={};drops=[];hand=new Item(payload.recipe.input,2);hand.nameTag='Original ingredient';hand.setLore(['foreign-lore']);run();assert.equal(hand.amount,1);assert.equal(state.cuts,0);hand=new Item('qa:knife');for(let n=0;n<4;n++)run();assert.equal(drops.length,0);assert.equal(hand.damage,4);run();const outputs=drops.map(e=>({id:e.getComponent().itemStack.typeId,count:e.getComponent().itemStack.amount}));assert.equal(outputs[0].id,payload.recipe.mode==='replace'?payload.recipe.result:payload.recipe.builtin.result);if(payload.recipe.mode==='supplement')assert.ok(outputs[1].count>=1&&outputs[1].count<=3);assert.deepEqual(state,{});assert.equal(hand.damage,4);cases.push({input:payload.recipe.input,cuts:4,releaseActions:1,outputs});}
// Destruction uses the actual host hook and refunds metadata, never skin.
state={};drops=[];hand=new Item('minecraft:chicken');hand.nameTag='Original ingredient';hand.setLore(['foreign-lore']);run();vm.runInContext('spillDirectStationContents',context)('kaleidoscope_cookery:chopping_board',block,state);assert.equal(drops.length,1);assert.equal(drops[0].getComponent().itemStack.nameTag,'Original ingredient');assert.deepEqual(drops[0].getComponent().itemStack.getRawLore(),['foreign-lore']);
fs.writeFileSync(report,JSON.stringify({schema:1,host:'reviewed author 1.0.8 + Board API 0.1.0',cases,destructionRefund:true,metadataPreserved:true,simulatedPlayers:false,native:false,client:false,boundary:'Actual patched registry and station bodies; storage-operation doubles only.'},null,2)+'\n');console.log('Reviewed host registry, board placement/cutting/release and destruction hooks PASS');
