import assert from 'node:assert/strict';
import {initial,restore,apply,advance,cancel,nextAction,view,flipSample,brushSample,seasonSample,TICKS,BITE_SECONDS} from './flow.js';
let passed=0;const check=(name,fn)=>{fn();passed++;console.log('PASS',name);};
const near=(a,b,e=1e-9)=>assert.ok(Math.abs(a-b)<e,`${a} != ${b}`);
let s=initial(),clock=0;
check('no display or sound on cold start',()=>{assert.equal(view(s,0).loaded,false);assert.equal(view(s,0).loop,false);});
check('wrong action no side effects',()=>{let r=apply(s,'flip',0);assert.equal(r.accepted,false);assert.equal(r.state,s);assert.deepEqual(r.events,[]);});
check('ignite does not start empty-grill cooking loop',()=>{s=apply(s,'ignite',clock).state;assert.equal(view(s,clock).loop,false);});
check('insert starts loop',()=>{s=apply(s,'insert',clock).state;assert.equal(view(s,clock).loop,true);});
check('brush uses original 20 ticks',()=>{s=apply(s,'brush',clock).state;assert.equal(s.action.ends,20);});
check('same-tick double input rejected',()=>{assert.equal(apply(s,'brush',clock).accepted,false);assert.equal(apply(s,'flip',clock).accepted,false);});
check('brush occupies full duration',()=>{s=advance(s,19).state;assert.equal(nextAction(s),'busy');s=advance(s,20).state;assert.equal(nextAction(s),'flip');});
check('four 700ms turns required',()=>{clock=20;for(let i=1;i<=4;i++){s=apply(s,'flip',clock).state;assert.equal(s.flips,i);assert.equal(s.action.ends-clock,14);clock+=14;s=advance(s,clock).state;}assert.equal(nextAction(s),'season');});
check('a fifth turn cannot be queued',()=>assert.equal(apply(s,'flip',clock).accepted,false));
check('season takes half a second',()=>{s=apply(s,'season',clock).state;assert.equal(s.action.ends-clock,10);clock+=10;s=advance(s,clock).state;});
check('take stops cooking loop',()=>{const r=apply(s,'take',clock);s=r.state;assert.equal(view(s,clock).loop,false);assert.ok(r.events.some(e=>e.kind==='stop_audio'));});
check('eat action locks for 90 ticks',()=>{s=apply(s,'eat',clock).state;assert.equal(s.action.ends-clock,90);});
for(let i=0;i<4;i++)check(`bite ${i+1} at original timestamp`,()=>{const a=s.action.started;const before=a+Math.ceil(BITE_SECONDS[i]*20)-1,after=before+1;assert.equal(view(s,before).bites,i);assert.equal(view(s,after).bites,i+1);});
check('late updates coalesce cues',()=>{const r=advance(s,clock+80);assert.equal(r.events.filter(e=>e.kind==='bite').length,1);assert.equal(r.events[0].coalesced,true);});
check('cancelling eating restores intact demo sample and stops sound',()=>{const r=cancel(s);assert.equal(r.state.phase,'taken');assert.equal(r.state.action,null);assert.equal(view(r.state,clock).bites,0);});
check('reloading does not replay an in-progress meal',()=>{const r=restore(JSON.stringify(s));assert.equal(r.phase,'taken');assert.equal(r.action,null);});
check('invalid and future save data not silently replaced',()=>{assert.throws(()=>restore('bad'));assert.throws(()=>restore('{"schema":2}'));});
check('completion has no food, item, nutrition or block-write effects',()=>{const r=advance(s,clock+90);assert.equal(r.state.phase,'finished');assert.ok(r.events.every(e=>['bite','action_end'].includes(e.kind)));});
check('different grill instances stay isolated',()=>{const a=initial(),b=initial();apply(a,'ignite',0);assert.deepEqual(b,initial());assert.deepEqual(a,initial());});
check('flip holds exact start and end orientations',()=>{for(let n=1;n<=4;n++){near(flipSample(0,.33,n).degrees,(n-1)*180);near(flipSample(.7,.33,n).degrees,n*180);near(flipSample(.7,.33,n).lift,0);}});
check('flip apex at 350ms',()=>{near(flipSample(.35,.33,2).lift,.33);near(flipSample(.35,.33,2).degrees,270);});
check('invalid heights and number rejected',()=>{assert.throws(()=>flipSample(.1,.5,1));assert.throws(()=>flipSample(.1,.33,0));});
check('brush sweeps both directions and returns',()=>{near(brushSample(.25).swing,1);near(brushSample(.75).swing,-1);near(brushSample(1).swing,0);});
check('brush left hand follows source, not naive entire vector negation',()=>{near(brushSample(.25,-1).position[0],-.27);near(brushSample(.25,-1).rotationXYZ[2],-66);});
check('season wave has two cycles',()=>{near(seasonSample(.0625).wave,1);near(seasonSample(.1875).wave,-1);near(seasonSample(.3125).wave,1);near(seasonSample(.4375).wave,-1);});
check('season retains extra bottle inversion',()=>near(seasonSample(0).rotationXYZ[2],202));
check('presentation state contains no item inventory',()=>assert.deepEqual(Object.keys(initial()).sort(),['schema','phase','flips','seq','action','lastCue'].sort()));
console.log(JSON.stringify({passed,failed:0,scope:'presentation rehearsal and source-equation checks; not Minecraft runtime acceptance'}));
