/** Actual runtime bodies with storage/event API doubles, never simulated players. */
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
import {stopSoundHandle} from '../../projects/grilling/gameplay_core/behavior_pack/scripts/immersion_audio_core.js';
import {commitSteps} from '../../projects/grilling/gameplay_core/behavior_pack/scripts/a277_grill_transaction_core.js';
import {slotWrite} from '../../projects/grilling/gameplay_core/behavior_pack/scripts/rack_transfer_plan.js';
import * as logic from '../../projects/grilling/gameplay_core/behavior_pack/scripts/core_logic.js';
import {configureItemDataWorld,setItemProperty} from '../../projects/grilling/gameplay_core/behavior_pack/scripts/itemDataCore.js';
import {captureEatingIdentity,eatingEventMatches} from '../../projects/grilling/gameplay_core/behavior_pack/scripts/a285_eating_transaction.js';
const metadata=new Map();configureItemDataWorld({getDynamicProperty:k=>metadata.get(k),setDynamicProperty:(k,v)=>metadata.set(k,v)});
const root=new URL('../../projects/grilling/gameplay_core/behavior_pack/scripts/',import.meta.url),source=fs.readFileSync(new URL('main.js',root),'utf8'),N='kaleidoscope_grilling:';
function fn(name){const start=source.indexOf('function '+name+'(');assert.ok(start>=0,name);let i=source.indexOf('{',start),depth=1,end=i+1;for(;depth&&end<source.length;end++){if(source[end]==='{')depth++;if(source[end]==='}')depth--;}return source.slice(start,end);}
class Stack{constructor(typeId,amount=1){this.typeId=typeId;this.amount=amount;this.maxAmount=64;this.props={};this.lore=[];}getRawLore(){return this.lore}setLore(v){this.lore=structuredClone(v)}clone(){return Object.assign(new Stack(this.typeId,this.amount),structuredClone({...this}));}}
function setup(){let fail=()=>false,quarantined=false,state={...logic.initialState(),lit:true,phase:2,seasoned:true};const drops=[],sounds=[];
 const storage=(name,size)=>({size,rows:Array(size),getItem(i){return this.rows[i]?.clone()},setItem(i,s){this.rows[i]=s?.clone();if(fail(name+':'+i))throw Error('injected '+name+':'+i);}}),grill=storage('grill',3),bag=storage('bag',4);
 const dimension={playSound(){},spawnItem(stack){const e={stack:stack.clone(),remove(){if(fail('remove'))throw Error('remove');drops.splice(drops.indexOf(e),1)}};drops.push(e);if(fail('spawn'))throw Error('spawn');return e;}},block={dimension,location:{x:0,y:0,z:0},x:0,y:0,z:0},holder={dimension,location:block.location};
 const ctx=vm.createContext({...logic,console:{warn(){}},ItemStack:Stack,commitSteps,slotWrite,inv:()=>{if(quarantined)throw Error('quarantined');return grill},readState:()=>structuredClone(state),writeState:(_b,s)=>{state=structuredClone(s);if(fail('state'))throw Error('state')},resetBlock:(_b,lit)=>{state={...logic.initialState(),lit};if(fail('state'))throw Error('state')},mainContainer:()=>bag,occupied:()=>grill.rows.filter(Boolean).length,outputFor:raw=>Object.assign(new Stack(N+'grilled_fish_skewer'),{props:structuredClone(raw.props)}),quarantineStation:()=>quarantined=true,blockSound:(_b,id)=>sounds.push(id),message(){},javaInteractionFeedback(){},interactionFailure(){}});
 vm.runInContext(fs.readFileSync(new URL('grill_transfer.js',root),'utf8').replace(/^import\b.*;\s*$/gm,'').replace(/export /g,'')+'\n'+fn('extract')+'\n'+fn('burnGrillContents')+'\nthis.api={extract,burnGrillContents};',ctx);
 return {grill,bag,block,holder,drops,sounds,api:ctx.api,get state(){return state},get quarantined(){return quarantined},once(key){let done=false;fail=k=>k===key&&!done&&(done=true)},fail(f){fail=f}};
}
for(const all of [false,true])test('extract '+(all?'all':'one')+' reserves distinct slots and resets only an empty grill',()=>{const f=setup();for(let i=0;i<3;i++){f.grill.rows[i]=new Stack(N+'raw_fish_skewer');f.grill.rows[i].props={marker:i};}assert.equal(f.api.extract(f.block,f.holder,all),all?3:1);assert.equal(f.grill.rows.filter(Boolean).length,all?0:2);assert.equal(f.bag.rows.filter(Boolean).length,all?3:1);assert.equal(f.state.phase,all?0:2);assert.equal(f.state.lit,true);assert.deepEqual(f.sounds,['pickup_item']);});
for(const key of ['grill:0','bag:0','state'])test('extract write-after-mutation '+key+' rolls inventories and state back',()=>{const f=setup();f.grill.rows[0]=new Stack(N+'raw_fish_skewer');f.once(key);assert.equal(f.api.extract(f.block,f.holder),0);assert.equal(f.grill.rows[0].typeId,N+'raw_fish_skewer');assert.equal(f.bag.rows.filter(Boolean).length,0);assert.equal(f.state.phase,2);assert.equal(f.quarantined,false);assert.deepEqual(f.sounds,[]);});
test('full backpack receives one acknowledged drop',()=>{const f=setup();f.grill.rows[0]=new Stack(N+'raw_fish_skewer');f.bag.rows.fill(new Stack('minecraft:stone',64));assert.equal(f.api.extract(f.block,f.holder),1);assert.equal(f.drops.length,1);assert.equal(f.grill.rows.filter(Boolean).length,0);});
test('unacknowledged drop quarantines and prevents automatic duplication',()=>{const f=setup();f.grill.rows[0]=new Stack(N+'raw_fish_skewer');f.bag.rows.fill(new Stack('minecraft:stone',64));f.once('spawn');assert.equal(f.api.extract(f.block,f.holder),0);assert.equal(f.quarantined,true);assert.throws(()=>f.api.extract(f.block,f.holder),/quarantined/);assert.equal(f.drops.length,1);});
test('multi-extract failure restores all raws and removes delivered outputs',()=>{const f=setup();f.grill.rows.fill(new Stack(N+'raw_fish_skewer'));f.once('bag:1');assert.equal(f.api.extract(f.block,f.holder,true),0);assert.equal(f.grill.rows.filter(Boolean).length,3);assert.equal(f.bag.rows.filter(Boolean).length,0);});
test('burn state failure removes charcoal and restores inputs',()=>{const f=setup();f.grill.rows.fill(new Stack(N+'raw_fish_skewer'));f.once('state');assert.equal(f.api.burnGrillContents(f.block,f.state,logic.initialState()),false);assert.equal(f.grill.rows.filter(Boolean).length,3);assert.equal(f.drops.length,0);assert.equal(f.state.phase,2);});
test('burn consumes three slots and emits one charcoal stack',()=>{const f=setup();f.grill.rows.fill(new Stack(N+'raw_fish_skewer'));assert.equal(f.api.burnGrillContents(f.block,f.state,{...logic.initialState(),lit:true}),true);assert.equal(f.grill.rows.filter(Boolean).length,0);assert.equal(f.drops.length,1);assert.ok([1,2].includes(f.drops[0].stack.amount));assert.equal(f.state.phase,0);});
test('rollback failure quarantines station',()=>{const f=setup();f.grill.rows[0]=new Stack(N+'raw_fish_skewer');f.fail(k=>k==='bag:0');assert.equal(f.api.extract(f.block,f.holder),0);assert.equal(f.quarantined,true);});
function threadFixture(id,amount,free=false,empty=false){let main=new Stack('minecraft:apple',4),off=new Stack(id,amount);off.props={original:'kept'};const outputs=[];const ctx=vm.createContext({ItemStack:Stack,heldMain:()=>main,heldOff:()=>off,captureWritableHand:(_,h)=>({before:(h==='main'?main:off).clone(),write:s=>{if(h==='main')main=s?.clone();else off=s?.clone()}}),threadOutcome:()=>({ok:true,id:N+'unfinished_skewer',kind:'unfinished'}),readSkewerRows:()=>empty?[]:[{id:'minecraft:apple'}],ingredientSnapshot:s=>({id:s.typeId}),restoreIngredient:r=>new Stack(r.id),writeSkewerRows:(s,r)=>{s.props.ingredients=JSON.stringify(r)},UNFINISHED_ID:N+'unfinished_skewer',SKEWER_INGREDIENTS_KEY:'ingredients',getItemProperty:(s,k)=>s.props[k],creative:()=>free,prepareOutputDelivery:(_,rows)=>({apply:()=>outputs.push(...rows),rollback:()=>outputs.length=0}),commitSteps,transactionStatus:r=>r.ok,awardLookingThePart(){},useSound(){},message(){},javaInteractionFeedback(){},interactionFailure(){}});vm.runInContext(fn('reducedStack')+'\n'+fn('threadCurrent')+'\nthis.run=threadCurrent',ctx);return {run:()=>ctx.run({playSound(){}}),outputs,get main(){return main},get off(){return off}};}
for(const id of ['minecraft:stick',N+'unfinished_skewer',N+'secret_skewer'])for(const free of [false,true])test('thread '+id+' retains native remainders '+free,()=>{const f=threadFixture(id,5,free);assert.equal(f.run(),true);assert.equal(f.off.amount,1);assert.equal(f.outputs[0].typeId,id);assert.equal(f.outputs[0].amount,free&&id==='minecraft:stick'?5:4);assert.equal(f.outputs[0].props.original,'kept');assert.equal(f.main.amount,free?4:3);});
for(const free of [false,true])test('empty starter consumption '+free,()=>{const f=threadFixture(N+'unfinished_skewer',5,free,true);assert.equal(f.run(),true);assert.equal(f.outputs[0].amount,free?5:4);});
function eatingFixture(){const handlers={},queue=[],active=new Map(),settled=new Map(),entity={id:'holder',selectedSlotIndex:0};let rewards=0,manual=0;const ctx=vm.createContext({world:{afterEvents:{itemCompleteUse:{subscribe:f=>handlers.complete=f},itemStopUse:{subscribe:f=>handlers.stop=f}}},system:{currentTick:100,run:f=>queue.push(f)},ACTIVE_EATS:active,SETTLED:settled,PLATE_EATS:new Map(),PENDING_USES:new Map(),CUISINE_EATS:new Map(),CUISINE_FOOD_SET:new Set(),FOOD_DATA:{[N+'grilled_fish_skewer']:{}},PENDING_SEASONING:'pending',PLATE_ID:'plate',SECRET_ID:N+'secret_skewer',now:()=>100,eatingEventMatches,RAW_NAUSEA:{},MYSTERIOUS_ID:'mysterious',DARK_ID:'dark',dangerousPreservation(){},stopSoundHandle,stopEatSound(){},afterCommitted(){rewards++},hungerSettle(){manual++;return true},addSecretNutrition(){rewards++},secretRemainders(){rewards++}});const start=source.indexOf('world.afterEvents.itemCompleteUse.subscribe'),end=source.indexOf('// Native use poses',start);vm.runInContext(source.slice(start,end),ctx);const event={source:entity,itemStack:new Stack(N+'grilled_fish_skewer')};function begin(){const a={id:event.itemStack.typeId,start:0,profile:'THREE_ALT',nativeDuration:100,use:captureEatingIdentity(event.itemStack,'main',0),meta:{}};active.set(entity.id,a);return a;}return {handlers,queue,active,event,begin,flush(){while(queue.length)queue.shift()()},get rewards(){return rewards},get manual(){return manual}};}
for(const order of ['complete-stop','stop-complete'])test('eating '+order+' settles once',()=>{const f=eatingFixture();f.begin();for(const h of order.split('-'))f.handlers[h](f.event);f.flush();assert.equal(f.rewards,1);assert.equal(f.manual,0);f.handlers.complete(f.event);assert.equal(f.rewards,1);});
test('interrupted use settles once and late completion grants no reward',()=>{const f=eatingFixture();f.begin();f.handlers.stop(f.event);f.handlers.stop(f.event);f.flush();assert.equal(f.manual,1);f.handlers.complete(f.event);assert.equal(f.rewards,0);});
test('old callback cannot debit new use',()=>{const f=eatingFixture();f.begin();f.handlers.stop(f.event);const next=f.begin();f.flush();assert.equal(f.active.get('holder'),next);assert.equal(f.manual,0);});
test('old completion cannot settle differently named new use',()=>{const f=eatingFixture();f.begin();f.handlers.complete(f.event);const old=f.event.itemStack;f.event.itemStack=new Stack(old.typeId);f.event.itemStack.nameTag='new';const next=f.begin();f.handlers.complete({...f.event,itemStack:old});assert.equal(f.rewards,1);assert.equal(f.active.get('holder'),next);});
test('early completion cannot settle a new use',()=>{const f=eatingFixture();const a=f.begin();a.start=95;f.handlers.complete(f.event);assert.equal(f.rewards,0);assert.equal(f.active.get('holder'),a);});
test('late old stop cannot cancel differently named new use',()=>{const f=eatingFixture();f.begin();f.handlers.complete(f.event);const old=f.event.itemStack;f.event.itemStack=new Stack(old.typeId);f.event.itemStack.nameTag='new';const next=f.begin();f.handlers.stop({...f.event,itemStack:old});f.flush();assert.equal(f.active.get('holder'),next);f.handlers.complete(f.event);assert.equal(f.rewards,2);});
for(const withStack of [false,true])test('same-tick old stop cannot cancel identical new use '+withStack,()=>{const f=eatingFixture();f.begin();f.handlers.complete(f.event);const next=f.begin();next.start=100;f.handlers.stop(withStack?f.event:{source:f.event.source});f.flush();assert.equal(f.active.get('holder'),next);assert.equal(f.manual,0);});
test('animation ticks never debit food',()=>{const interval=source.slice(source.indexOf('system.runInterval(()=>{\n for(const p'));assert.ok(!interval.includes('hungerSettle('));});
test('natural heat expiry accepted, premature expiry and other metadata rejected',()=>{const s=new Stack(N+'secret_skewer');setItemProperty(s,N+'hot_until',100);setItemProperty(s,N+'skewer_ingredients','apple');const use=captureEatingIdentity(s,'main',0),cold=s.clone();setItemProperty(cold,N+'hot_until',undefined);assert.equal(eatingEventMatches(use,cold,99),false);assert.equal(eatingEventMatches(use,cold,100),true);setItemProperty(cold,N+'skewer_ingredients','poison');assert.equal(eatingEventMatches(use,cold,101),false);});
test('thread remainder delivery refuses full inventory without world drops',()=>{const rows=[new Stack('minecraft:stone',64)],bag={size:1,getItem:i=>rows[i]?.clone(),setItem:(i,s)=>rows[i]=s?.clone()};const ctx=vm.createContext({mainContainer:()=>bag,mergeIntoContainer:(_c,s)=>s});vm.runInContext(fn('prepareOutputDelivery')+';this.api=prepareOutputDelivery',ctx);const r=commitSteps([ctx.api({},[new Stack(N+'unfinished_skewer',63)])]);assert.equal(r.ok,false);assert.equal(r.rollbackErrors,0);assert.equal(rows[0].amount,64);});
test('starter recipe does not offer metadata-blind reverse crafting',()=>{const dir=new URL('../recipes/',root),recipes=fs.readdirSync(dir).map(f=>JSON.parse(fs.readFileSync(new URL(f,dir),'utf8'))),r=recipes.find(x=>x['minecraft:recipe_shapeless']?.description.identifier===N+'skewer_starter')['minecraft:recipe_shapeless'];assert.deepEqual(r.ingredients,[{item:'minecraft:stick'}]);assert.deepEqual(r.result,{item:N+'unfinished_skewer',count:1});assert.ok(!recipes.some(x=>JSON.stringify(x).includes('"ingredients":[{"item":"'+N+'unfinished_skewer')));});
test('complete grill state cycle retains cooldown through serialization',()=>{let s=logic.brush(logic.light(logic.initialState(),true),3,1200).state;for(let i=0;i<4;i++){assert.equal(logic.flip(s).ok,true);s=logic.flip(s).state;if(i<3){assert.equal(logic.flip(s).ok,false);s=logic.normalizeState(JSON.parse(JSON.stringify(logic.tickState(s,3,20).state)));}}s=logic.season(s,3,[N+'cumin']).state;assert.equal(logic.canExtract(s),true);assert.equal(logic.outputKind(s),'cooked');assert.equal(s.flips,4);});
