import assert from 'node:assert/strict';
import {initialState,tickState,light,brush,flip,season,canInsert,canExtract,breakDisposition,outputKind,FINISHED_TICKS,BURNT_TICKS,FLIP_COOLDOWN} from './core_logic.js';
let n=0;const t=(name,fn)=>{fn();n++;console.log('PASS',name)};
t('initial',()=>assert.deepEqual(initialState(),{phase:0,phaseTicks:0,flips:0,flipCooldown:0,seasoned:false,failed:false,heatTicks:0,lit:false}));
let s=light(initialState(),true);
t('lit accepts insertion',()=>assert.equal(canInsert(s,0),true));
t('unlit rejects insertion',()=>assert.equal(canInsert(initialState(),0),false));
let b=brush(s,3,1200);s=b.state;
t('brush starts phase1',()=>{assert.equal(b.ok,true);assert.equal(s.phase,1);assert.equal(s.heatTicks,1200)});
let f=flip(s);s=f.state;
t('first flip adds cooldown',()=>{assert.equal(s.flips,1);assert.equal(s.flipCooldown,FLIP_COOLDOWN)});
t('cooldown rejects spam',()=>assert.equal(flip(s).ok,false));
s=tickState(s,3,20).state;
for(let i=0;i<3;i++){s=flip(s).state;s=tickState(s,3,20).state}
t('four flips reach phase2',()=>assert.equal(s.phase,2));
t('cannot extract before seasoning',()=>assert.equal(canExtract(s),false));
s=season(s,3).state;
t('season unlocks extraction',()=>{assert.equal(s.seasoned,true);assert.equal(canExtract(s),true);assert.equal(outputKind(s),'cooked')});
let timeout=light(initialState(),true);timeout=brush(timeout,1,1200).state;
timeout=tickState(timeout,1,FINISHED_TICKS).state;
t('any unfinished phase times out to phase3',()=>assert.equal(timeout.phase,3));
t('phase3 extracts dark',()=>assert.equal(outputKind(timeout),'dark'));
let burn=tickState(timeout,1,BURNT_TICKS);
t('phase3 burns to charcoal and resets',()=>{assert.ok(burn.events.some(e=>e.kind==='burn_to_charcoal'));assert.deepEqual(burn.state,initialState())});
t('break phase0 returns raw',()=>assert.equal(breakDisposition(light(initialState(),true)),'raw'));
t('break brushed/unfinished returns mysterious',()=>assert.equal(breakDisposition(brush(light(initialState(),true),1,1200).state),'mysterious'));
t('break seasoned cooked returns cooked',()=>assert.equal(breakDisposition(s),'cooked'));
t('break overcooked returns dark',()=>assert.equal(breakDisposition(timeout),'dark'));
console.log(JSON.stringify({passed:n,failed:0,scope:'Java GrillBlockEntity phase/flips/timeout/break disposition core'}));
