import {isPendingSeasoningId} from '../../projects/grilling/gameplay_core/behavior_pack/scripts/a2743_seasoning_contract_core.js';
import {canonicalFoodId} from '../../projects/grilling/gameplay_core/behavior_pack/scripts/eating_profile_ids.js';
/** Actual runtime bodies with storage/event API doubles, never simulated players. */
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
import {stopSoundHandle} from '../../projects/grilling/gameplay_core/behavior_pack/scripts/immersion_audio_core.js';
import {commitSteps} from '../../projects/grilling/gameplay_core/behavior_pack/scripts/a277_grill_transaction_core.js';
import {slotWrite,planInventoryInsert} from '../../projects/grilling/gameplay_core/behavior_pack/scripts/rack_transfer_plan.js';
import {nativeItemSignature,ownedItemStep,planOwnedInventoryDelivery,commitPlayerItemTransaction} from '../../projects/grilling/gameplay_core/behavior_pack/scripts/owned_item_transaction_core.js';
import {captureSkewerMetadata,restoreSkewerMetadata} from '../../projects/grilling/gameplay_core/behavior_pack/scripts/skewer_item_snapshot.js';
import {SECRET_MODEL_VARIANTS_KEY,appendedModelVariants} from '../../projects/grilling/gameplay_core/behavior_pack/scripts/secret_visual_state_core.js';
import * as logic from '../../projects/grilling/gameplay_core/behavior_pack/scripts/core_logic.js';
import {configureItemDataWorld,setItemProperty} from '../../projects/grilling/gameplay_core/behavior_pack/scripts/itemDataCore.js';
import {captureEatingIdentity,eatingEventMatches} from '../../projects/grilling/gameplay_core/behavior_pack/scripts/a285_eating_transaction.js';
import {finishedFoodMeta} from '../../projects/grilling/gameplay_core/behavior_pack/scripts/food_finish_core.js';
import {nativeEatingCompleted} from '../../projects/grilling/gameplay_core/behavior_pack/scripts/player_presentation_core.js';
const metadata=new Map();configureItemDataWorld({getDynamicProperty:k=>metadata.get(k),setDynamicProperty:(k,v)=>metadata.set(k,v)});
const root=new URL('../../projects/grilling/gameplay_core/behavior_pack/scripts/',import.meta.url),source=fs.readFileSync(new URL('main.js',root),'utf8'),N='kaleidoscope_grilling:';
function fn(name){const start=source.indexOf('function '+name+'(');assert.ok(start>=0,name);let i=source.indexOf('{',start),depth=1,end=i+1;for(;depth&&end<source.length;end++){if(source[end]==='{')depth++;if(source[end]==='}')depth--;}return source.slice(start,end);}
class Stack{constructor(typeId,amount=1){this.typeId=typeId;this.amount=amount;this.maxAmount=64;this.props={};this.lore=[];this.keepOnDeath=false;this.lockMode='none'}getRawLore(){return this.lore}setLore(v){this.lore=structuredClone(v)}clone(){return Object.assign(new Stack(this.typeId,this.amount),structuredClone({...this}));}isStackableWith(other){if(!other)return false;const {amount,...own}=this,{amount:otherAmount,...theirs}=other;return JSON.stringify(own)===JSON.stringify(theirs)}getCanDestroy(){return this.destroy??[]}getCanPlaceOn(){return this.place??[]}setCanDestroy(v){this.destroy=[...v]}setCanPlaceOn(v){this.place=[...v]}getComponent(){return undefined}getDynamicPropertyIds(){return Object.keys(this.props)}getDynamicProperty(k){return this.props[k]}setDynamicProperty(k,v){this.props[k]=v}}
function setup(){let fail=()=>false,quarantined=false,state={...logic.initialState(),lit:true,phase:2,seasoned:true};const drops=[],sounds=[];
 const storage=(name,size)=>({size,rows:Array(size),getItem(i){return this.rows[i]?.clone()},setItem(i,s){this.rows[i]=s?.clone();if(fail(name+':'+i))throw Error('injected '+name+':'+i);}}),grill=storage('grill',3),bag=storage('bag',4);
 const dimension={playSound(){},spawnItem(stack){const e={stack:stack.clone(),remove(){if(fail('remove'))throw Error('remove');drops.splice(drops.indexOf(e),1)}};drops.push(e);if(fail('spawn'))throw Error('spawn');return e;}},block={dimension,location:{x:0,y:0,z:0},x:0,y:0,z:0},holder={dimension,location:block.location};
 const ctx=vm.createContext({isPendingSeasoningId,SECRET_MODEL_VARIANTS_KEY,appendedModelVariants,setItemProperty:(s,k,v)=>{s.props[k]=v},canonicalFoodId,forgetEatingItem(){},...logic,console:{warn(){}},ItemStack:Stack,commitSteps,slotWrite,planInventoryInsert,inv:()=>{if(quarantined)throw Error('quarantined');return grill},readState:()=>structuredClone(state),writeState:(_b,s)=>{state=structuredClone(s);if(fail('state'))throw Error('state')},resetBlock:(_b,lit)=>{state={...logic.initialState(),lit};if(fail('state'))throw Error('state')},mainContainer:()=>bag,occupied:()=>grill.rows.filter(Boolean).length,outputFor:raw=>Object.assign(new Stack(N+'grilled_fish_skewer'),{props:structuredClone(raw.props)}),quarantineStation:()=>quarantined=true,blockSound:(_b,id)=>sounds.push(id),message(){},javaInteractionFeedback(){},interactionFailure(){}});
 vm.runInContext(fs.readFileSync(new URL('grill_transfer.js',root),'utf8').replace(/^import\b.*;\s*$/gm,'').replace(/export /g,'')+'\n'+fn('extract')+'\n'+fn('burnGrillContents')+'\nthis.api={extract,burnGrillContents};',ctx);
 return {grill,bag,block,holder,drops,sounds,api:ctx.api,get state(){return state},get quarantined(){return quarantined},once(key){let done=false;fail=k=>k===key&&!done&&(done=true)},fail(f){fail=f}};
}
for(const all of [false,true])test('extract '+(all?'all':'one')+' reserves distinct slots and resets only an empty grill',()=>{const f=setup();for(let i=0;i<3;i++){f.grill.rows[i]=new Stack(N+'raw_fish_skewer');f.grill.rows[i].props={marker:i};}assert.equal(f.api.extract(f.block,f.holder,all),all?3:1);assert.equal(f.grill.rows.filter(Boolean).length,all?0:2);assert.equal(f.bag.rows.filter(Boolean).length,all?3:1);assert.equal(f.state.phase,all?0:2);assert.equal(f.state.lit,true);assert.deepEqual(f.sounds,['pickup_item']);});
for(const key of ['grill:0','bag:0','state'])test('extract write-after-mutation '+key+' rolls inventories and state back',()=>{const f=setup();f.grill.rows[0]=new Stack(N+'raw_fish_skewer');f.once(key);assert.equal(f.api.extract(f.block,f.holder),0);assert.equal(f.grill.rows[0].typeId,N+'raw_fish_skewer');assert.equal(f.bag.rows.filter(Boolean).length,0);assert.equal(f.state.phase,2);assert.equal(f.quarantined,false);assert.deepEqual(f.sounds,[]);});
test('full backpack receives one acknowledged drop',()=>{const f=setup();f.grill.rows[0]=new Stack(N+'raw_fish_skewer');f.bag.rows.fill(new Stack('minecraft:stone',64));assert.equal(f.api.extract(f.block,f.holder),1);assert.equal(f.drops.length,1);assert.equal(f.grill.rows.filter(Boolean).length,0);});
test('unacknowledged drop quarantines and prevents automatic duplication',()=>{const f=setup();f.grill.rows[0]=new Stack(N+'raw_fish_skewer');f.bag.rows.fill(new Stack('minecraft:stone',64));f.once('spawn');assert.equal(f.api.extract(f.block,f.holder),0);assert.equal(f.quarantined,true);assert.throws(()=>f.api.extract(f.block,f.holder),/quarantined/);assert.equal(f.drops.length,1);});
test('multi-extract failure restores all raws and removes delivered outputs',()=>{const f=setup();for(let i=0;i<3;i++){f.grill.rows[i]=new Stack(N+'raw_fish_skewer');f.grill.rows[i].props={marker:i};}const before=structuredClone(f.grill.rows);f.once('bag:1');assert.equal(f.api.extract(f.block,f.holder,true),0);assert.equal(f.grill.rows.filter(Boolean).length,3);assert.deepEqual(structuredClone(f.grill.rows),before);assert.equal(f.bag.rows.filter(Boolean).length,0);});
test('burn state failure removes charcoal and restores inputs',()=>{const f=setup();f.grill.rows.fill(new Stack(N+'raw_fish_skewer'));f.once('state');assert.equal(f.api.burnGrillContents(f.block,f.state,logic.initialState()),false);assert.equal(f.grill.rows.filter(Boolean).length,3);assert.equal(f.drops.length,0);assert.equal(f.state.phase,2);});
test('burn consumes three slots and emits one charcoal stack',()=>{const f=setup();f.grill.rows.fill(new Stack(N+'raw_fish_skewer'));assert.equal(f.api.burnGrillContents(f.block,f.state,{...logic.initialState(),lit:true}),true);assert.equal(f.grill.rows.filter(Boolean).length,0);assert.equal(f.drops.length,1);assert.ok([1,2].includes(f.drops[0].stack.amount));assert.equal(f.state.phase,0);});
test('rollback failure quarantines station',()=>{const f=setup();f.grill.rows[0]=new Stack(N+'raw_fish_skewer');f.fail(k=>k==='bag:0');assert.equal(f.api.extract(f.block,f.holder),0);assert.equal(f.quarantined,true);});
function threadFixture(id,amount,free=false,empty=false,{full=false}={}){
 let off=new Stack(id,amount),fault=()=>false,spawns=0;off.props={original:'kept'};
 const rows=[new Stack('minecraft:apple',4),full?new Stack('minecraft:stone',64):undefined,full?new Stack('minecraft:stone',64):undefined],drops=[],dp=new Map();
 const ingredient=new Stack('minecraft:carrot');ingredient.nameTag='recorded carrot';ingredient.lore=[{text:'native recipe ingredient'}];ingredient.place=['minecraft:dirt'];
 let ingredients=empty?[]:[{id:ingredient.typeId,native:captureSkewerMetadata(ingredient)}];
 const fail=(kind,value)=>{if(fault(kind,value))throw Error('injected '+kind)};
 const bag={size:rows.length,getItem:slot=>rows[slot]?.clone(),setItem(slot,stack){rows[slot]=stack?.clone();fail('slot'+slot,stack)}};
 const world={getDynamicProperty:key=>dp.get(key),setDynamicProperty(key,value){if(value===undefined)dp.delete(key);else dp.set(key,value);fail('property',value)}};
 const dimension={spawnItem(stack){
  const number=++spawns,entity={number,stack:stack.clone(),isValid:true,getComponent(){fail('dropRead',this);return {itemStack:this.stack.clone()}},remove(){fail('remove',this);this.isValid=false;drops.splice(drops.indexOf(this),1)}};
  drops.push(entity);fail('spawn',entity);return entity;
 }};
 const holder={id:'thread-player',name:'tester',selectedSlotIndex:0,dimension,location:{x:0,y:64,z:0},playSound(){}};
 function load(){
  const ctx=vm.createContext({isPendingSeasoningId,SECRET_MODEL_VARIANTS_KEY,appendedModelVariants,setItemProperty:(s,k,v)=>{s.props[k]=v},canonicalFoodId,forgetEatingItem(){},ItemStack:Stack,EnchantmentType:class{constructor(id){this.id=id}},restoreSkewerMetadata,metadataSignature:JSON.stringify,nativeItemSignature,ownedItemStep,planOwnedInventoryDelivery,commitPlayerItemTransaction,
   world:{...world},system:{currentTick:1},console:{warn(){}},mainContainer:()=>bag,heldMain:()=>rows[0]?.clone(),heldOff:()=>off?.clone(),
   captureWritableHand(_,hand){const read=()=>hand==='main'?bag.getItem(0):off?.clone();return {before:read(),read,write(stack){if(hand==='main')bag.setItem(0,stack);else{off=stack?.clone();fail('off',stack)}}}},
   threadOutcome:()=>({ok:true,id:N+'unfinished_skewer',kind:'unfinished'}),readSkewerRows:()=>structuredClone(ingredients),canDisassembleOff:()=>!!off&&off.amount>0,ingredientSnapshot:stack=>({id:stack.typeId,native:captureSkewerMetadata(stack)}),writeSkewerRows:(s,r)=>{s.props.ingredients=JSON.stringify(r)},UNFINISHED_ID:N+'unfinished_skewer',SKEWER_INGREDIENTS_KEY:'ingredients',getItemProperty:(s,k)=>s.props[k],creative:()=>free,commitSteps,transactionStatus:r=>r.ok,awardLookingThePart(){},useSound(){},message(){},javaInteractionFeedback(){},interactionFailure(){}});
  vm.runInContext(['reducedStack','restoreIngredient','prepareOutputDelivery','threadCurrent','disassembleOff'].map(fn).join('\n')+';this.run=threadCurrent;this.disassemble=disassembleOff',ctx);return ctx;
 }
 let ctx=load();return {run:()=>ctx.run(holder),disassemble:()=>ctx.disassemble(holder),rows,drops,dp,holder,ingredient,get outputs(){return [...rows.slice(1).filter(s=>s&&s.typeId!=='minecraft:stone'),...drops.map(e=>e.stack)]},get main(){return rows[0]},get off(){return off},set off(stack){off=stack?.clone()},setFault(fn){fault=fn},setIngredients(value){ingredients=value},reload(){ctx=load()}};
}
for(const id of ['minecraft:stick',N+'unfinished_skewer',N+'secret_skewer'])for(const free of [false,true])test('thread '+id+' retains native remainders '+free,()=>{const f=threadFixture(id,5,free);assert.equal(f.run(),true);assert.equal(f.off.amount,1);assert.equal(f.outputs[0].typeId,id);assert.equal(f.outputs[0].amount,free&&id==='minecraft:stick'?5:4);assert.equal(f.outputs[0].props.original,'kept');assert.equal(f.main.amount,free?4:3);});
for(const free of [false,true])test('empty starter consumption '+free,()=>{const f=threadFixture(N+'unfinished_skewer',5,free,true);assert.equal(f.run(),true);assert.equal(f.outputs[0].amount,free?5:4);});
function eatingFixture(){const handlers={},queue=[],active=new Map(),settled=new Map(),entity={id:'holder',selectedSlotIndex:0};let rewards=0,manual=0;const ctx=vm.createContext({isPendingSeasoningId,SECRET_MODEL_VARIANTS_KEY,appendedModelVariants,setItemProperty:(s,k,v)=>{s.props[k]=v},canonicalFoodId,forgetEatingItem(){},world:{afterEvents:{itemCompleteUse:{subscribe:f=>handlers.complete=f},itemStopUse:{subscribe:f=>handlers.stop=f}}},system:{currentTick:100,run:f=>queue.push(f)},ACTIVE_EATS:active,SETTLED:settled,PLATE_EATS:new Map(),PENDING_USES:new Map(),CUISINE_EATS:new Map(),CUISINE_FOOD_SET:new Set(),FOOD_DATA:{[N+'grilled_fish_skewer']:{}},PENDING_SEASONING:'pending',PLATE_ID:'plate',SECRET_ID:N+'secret_skewer',now:()=>100,eatingEventMatches,nativeEatingCompleted,finishedFoodMeta,RAW_NAUSEA:{},MYSTERIOUS_ID:'mysterious',DARK_ID:'dark',dangerousPreservation(){},stopSoundHandle,stopEatSound(){},afterCommitted(){rewards++},hungerSettle(){manual++;return true},addSecretNutrition(){rewards++},secretRemainders(){rewards++}});const start=source.indexOf('world.afterEvents.itemCompleteUse.subscribe'),end=source.indexOf('// Native use poses',start);vm.runInContext((source.match(/const MINIMUM_EAT_TICKS=\d+,RELEASE_CHECKPOINT_GRACE_TICKS=\d+;/)?.[0]??'')+'\n'+source.slice(start,end),ctx);const event={source:entity,itemStack:new Stack(N+'grilled_fish_skewer'),useDuration:0};function begin(){const a={id:event.itemStack.typeId,start:0,profile:'THREE_ALT',nativeDuration:100,use:captureEatingIdentity(event.itemStack,'main',0),meta:{}};active.set(entity.id,a);return a;}return {handlers,queue,active,event,begin,flush(){while(queue.length)queue.shift()()},get rewards(){return rewards},get manual(){return manual}};}
for(const order of ['complete-stop','stop-complete'])test('eating '+order+' settles once',()=>{const f=eatingFixture();f.begin();for(const h of order.split('-'))f.handlers[h](f.event);f.flush();assert.equal(f.rewards,1);assert.equal(f.manual,0);f.handlers.complete(f.event);assert.equal(f.rewards,1);});
test('interrupted use settles once and late completion grants no reward',()=>{const f=eatingFixture();f.begin();f.handlers.stop(f.event);f.handlers.stop(f.event);f.flush();assert.equal(f.manual,1);f.handlers.complete(f.event);assert.equal(f.rewards,0);});
test('old callback cannot debit new use',()=>{const f=eatingFixture();f.begin();f.handlers.stop(f.event);const next=f.begin();f.flush();assert.equal(f.active.get('holder'),next);assert.equal(f.manual,0);});
test('old completion cannot settle differently named new use',()=>{const f=eatingFixture();f.begin();f.handlers.complete(f.event);const old=f.event.itemStack;f.event.itemStack=new Stack(old.typeId);f.event.itemStack.nameTag='new';const next=f.begin();f.handlers.complete({...f.event,itemStack:old});assert.equal(f.rewards,1);assert.equal(f.active.get('holder'),next);});
test('early completion cannot settle a new use',()=>{const f=eatingFixture();const a=f.begin();a.start=95;f.handlers.complete(f.event);assert.equal(f.rewards,0);assert.equal(f.active.get('holder'),a);});
test('late old stop cannot cancel differently named new use',()=>{const f=eatingFixture();f.begin();f.handlers.complete(f.event);const old=f.event.itemStack;f.event.itemStack=new Stack(old.typeId);f.event.itemStack.nameTag='new';const next=f.begin();f.handlers.stop({...f.event,itemStack:old});f.flush();assert.equal(f.active.get('holder'),next);f.handlers.complete(f.event);assert.equal(f.rewards,2);});
for(const withStack of [false,true])test('same-tick old stop cannot cancel identical new use '+withStack,()=>{const f=eatingFixture();f.begin();f.handlers.complete(f.event);const next=f.begin();next.start=100;f.handlers.stop(withStack?f.event:{source:f.event.source});f.flush();assert.equal(f.active.get('holder'),next);assert.equal(f.manual,0);});
test('animation ticks never debit food',()=>{const interval=source.slice(source.indexOf('system.runInterval(()=>{\n for(const p'));assert.ok(!interval.includes('hungerSettle('));});
test('natural heat expiry accepted, premature expiry and other metadata rejected',()=>{const s=new Stack(N+'secret_skewer');setItemProperty(s,N+'hot_until',100);setItemProperty(s,N+'skewer_ingredients','apple');const use=captureEatingIdentity(s,'main',0),cold=s.clone();setItemProperty(cold,N+'hot_until',undefined);assert.equal(eatingEventMatches(use,cold,99),false);assert.equal(eatingEventMatches(use,cold,100),true);setItemProperty(cold,N+'skewer_ingredients','poison');assert.equal(eatingEventMatches(use,cold,101),false);});
test('full inventory threads once and drops only the actual remaining sticks',()=>{
 const f=threadFixture('minecraft:stick',5,false,true,{full:true});assert.equal(f.run(),true);assert.equal(f.main.amount,3);assert.equal(f.off.typeId,N+'unfinished_skewer');assert.equal(f.off.amount,1);assert.equal(f.drops.length,1);assert.equal(f.drops[0].stack.typeId,'minecraft:stick');assert.equal(f.drops[0].stack.amount,4);assert.equal(f.dp.size,0);
});
test('full inventory disassembly returns native ingredient metadata and one stick exactly once',()=>{
 const f=threadFixture(N+'unfinished_skewer',1,false,false,{full:true});assert.equal(f.disassemble(),true);assert.equal(f.off,undefined);assert.equal(f.drops.length,2);
 assert.deepEqual(captureSkewerMetadata(f.drops[0].stack),captureSkewerMetadata(f.ingredient));assert.equal(f.drops[1].stack.typeId,'minecraft:stick');assert.equal(f.drops[1].stack.amount,1);assert.equal(f.disassemble(),false);assert.equal(f.drops.length,2);
});
test('known threading write failures restore owned hands and all acknowledged credits',()=>{
 for(const target of ['slot0','off','slot1','dropRead']){
  const f=threadFixture('minecraft:stick',5,false,true,{full:target==='dropRead'}),oldMain=f.main.clone(),oldOff=f.off.clone();let once=true;
  f.setFault(key=>key===target&&once&&(once=false,true));assert.equal(f.run(),false);assert.deepEqual(f.main,oldMain);assert.deepEqual(f.off,oldOff);assert.equal(f.drops.length,0);assert.equal(f.dp.size,0);
 }
});
test('unknown thread drop retains both input debits and prevents repeated or reloaded settlement',()=>{
 const f=threadFixture('minecraft:stick',5,false,true,{full:true});let once=true;f.setFault(key=>key==='spawn'&&once&&(once=false,true));assert.equal(f.run(),false);
 assert.equal(f.main.amount,3);assert.equal(f.off.typeId,N+'unfinished_skewer');assert.equal(f.drops.length,1);assert.equal(f.drops[0].stack.amount,4);assert.equal(f.dp.size,1);
 assert.throws(f.run,/requires recovery/);assert.throws(f.disassemble,/requires recovery/);f.reload();assert.throws(f.run,/requires recovery/);assert.equal(f.drops.length,1);
});
test('failed offhand credit recovery prevents the earlier main ingredient refund',()=>{
 const f=threadFixture('minecraft:stick',5,false,true);let once=true;
 f.setFault(key=>{if(key!=='slot1'||!once)return false;once=false;const foreign=f.off.clone();foreign.nameTag='foreign offhand owner';f.off=foreign;return true});
 assert.equal(f.run(),false);assert.equal(f.main.amount,3);assert.equal(f.off.nameTag,'foreign offhand owner');assert.equal(f.rows[1],undefined);assert.equal(f.dp.size,1);
});
test('later disassembly spawn failure rolls back known earlier outputs without refunding the consumed skewer',()=>{
 const f=threadFixture(N+'unfinished_skewer',1,false,false,{full:true});f.setIngredients(['minecraft:carrot','minecraft:beef','minecraft:potato'].map(id=>({id,native:captureSkewerMetadata(new Stack(id))})));
 let once=true;f.setFault((key,e)=>key==='spawn'&&e.number===2&&once&&(once=false,true));assert.equal(f.disassemble(),false);assert.equal(f.off,undefined);assert.equal(f.drops.length,1);assert.equal(f.drops[0].stack.typeId,'minecraft:beef');assert.equal(f.dp.size,1);
 f.reload();f.off=new Stack(N+'unfinished_skewer');assert.throws(f.disassemble,/requires recovery/);assert.equal(f.drops.length,1);
});
function readRecipes(dir){return fs.readdirSync(dir,{withFileTypes:true}).flatMap(entry=>entry.isDirectory()?readRecipes(new URL(entry.name+'/',dir)):entry.isFile()&&entry.name.endsWith('.json')?[JSON.parse(fs.readFileSync(new URL(entry.name,dir),'utf8'))]:[])}
test('starter recipe does not offer metadata-blind reverse crafting',()=>{const recipes=readRecipes(new URL('../recipes/',root)),r=recipes.find(x=>x['minecraft:recipe_shapeless']?.description.identifier===N+'skewer_starter')['minecraft:recipe_shapeless'];assert.deepEqual(r.ingredients,[{item:'minecraft:stick'}]);assert.deepEqual(r.result,{item:N+'unfinished_skewer',count:1});assert.ok(!recipes.some(x=>JSON.stringify(x).includes('"ingredients":[{"item":"'+N+'unfinished_skewer')));});
test('complete grill state cycle retains cooldown through serialization',()=>{let s=logic.brush(logic.light(logic.initialState(),true),3,1200).state;for(let i=0;i<4;i++){assert.equal(logic.flip(s).ok,true);s=logic.flip(s).state;if(i<3){assert.equal(logic.flip(s).ok,false);s=logic.normalizeState(JSON.parse(JSON.stringify(logic.tickState(s,3,20).state)));}}s=logic.season(s,3,[N+'cumin']).state;assert.equal(logic.canExtract(s),true);assert.equal(logic.outputKind(s),'cooked');assert.equal(s.flips,4);});
