/** New production before-hurt/deferred sequences with storage/API-operation
 * doubles. These are not Minecraft players or native collision-order proof. */
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
import * as lifecycle from '../../projects/grilling/gameplay_core/behavior_pack/scripts/effect_lifecycle_core.js';
import {tryProjectileDodgeMovement as move} from '../../projects/grilling/gameplay_core/behavior_pack/scripts/projectile_dodge_movement_runtime.js';
const base=new URL('../../projects/grilling/gameplay_core/behavior_pack/scripts/',import.meta.url),read=n=>fs.readFileSync(new URL(n,base),'utf8');
const strip=s=>s.replace(/^import\b[\s\S]*?;\s*/gm,'').replace(/\bexport (?=(class|const|function|async))/g,'').replace(/^export \{[^}]*\};/gm,'');
const baseline=JSON.parse(fs.readFileSync(new URL('../../tools/fixtures/g84-projectile-dodge-before.json',import.meta.url),'utf8'));
const main=read('main.js'),fx=main.slice(main.indexOf('function readFx('),main.indexOf('function fxSnapshot('));
const before=main.slice(main.indexOf('world.beforeEvents.entityHurt.subscribe(e=>{'),main.indexOf('world.afterEvents.playerSpawn.subscribe(e=>{'));
function fixture(remaining=200,{old=false,teleportSuccess=true}={}){
 const state={time:1000,restricted:false,raw:remaining?JSON.stringify({projectile_dodge:{until:1000+remaining,amp:0}}):undefined,valid:true,dimensionId:'minecraft:overworld',health:20,location:{x:0,y:80,z:0},writes:0,beforeWrites:0,teleports:0,sounds:0,invincibleFeedback:0};
 const queue=[],signals={},log=[];let hitCallback,writeFault,readFault,teleportHook,scheduleFault;
 const signal=name=>({subscribe:f=>(signals[name]??=[]).push(f)}),system={currentTick:1000,run(f){if(scheduleFault==='after'){queue.push(f);throw Error('schedule after-queue fault')}if(scheduleFault)throw Error('schedule fault');queue.push(f)}};
 const world={getAbsoluteTime:()=>{if(state.clockFailure)throw Error('world clock unavailable');return state.time},beforeEvents:{entityHurt:{subscribe:f=>hitCallback=f}},afterEvents:{playerLeave:signal('leave'),playerSpawn:signal('spawn'),entityDie:signal('death'),entityRemove:signal('remove')}};
 // These reservation cases need an independently specified native floor so a
 // successful move can reach the existing debit/reentry/audio assertions.
 const dimension={get id(){return state.dimensionId},heightRange:{min:-64,max:320},isChunkLoaded:()=>true,getBlock:point=>{
  const typeId=point.y<80?'minecraft:stone':'minecraft:air',states=point.y<80?{stone_type:'stone'}:{};
  return {typeId,isLiquid:false,isWaterlogged:false,permutation:{type:{id:typeId},getAllStates:()=>({...states})}};
 },playSound(){state.sounds++}};
 function wrapper(){return {id:'native-operation-subject',get isValid(){return state.valid},get dimension(){return dimension},get location(){return {...state.location}},getAABB:()=>({center:{x:state.location.x,y:state.location.y+.65,z:state.location.z},extent:{x:.45,y:.65,z:.45}}),setProperty(){},getComponent:id=>id==='minecraft:health'?{currentValue:state.health}:undefined,getDynamicProperty:key=>{if(key!==lifecycle.FX_KEY)return undefined;if(readFault)readFault();return state.raw},
 setDynamicProperty(key,value){if(state.restricted){state.beforeWrites++;throw Error('native write in before-event')}if(key!==lifecycle.FX_KEY)return;state.writes++;if(writeFault)return writeFault(value);state.raw=value},
 tryTeleport(location){state.teleports++;if(teleportHook)teleportHook();if(teleportSuccess){state.location={...location};return true}return false}}}
 const entity=wrapper(),console={warn:s=>log.push(String(s))};
 const runtime=vm.createContext({...lifecycle,world,system,nativeDragonHealth(){},console});vm.runInContext(strip(read('effect_state_runtime.js')),runtime);
 const effects=vm.runInContext('({readEffects,writeEffects,clearEffects,effectTime,projectileDodgeTime,readProjectileDodgeState,debitProjectileDodge,forgetProjectileDodgeState})',runtime);
 const reservation=vm.createContext({...effects,effectTime:effects.projectileDodgeTime,console});vm.runInContext(strip(read('projectile_dodge_runtime.js')),reservation);
 const api=vm.runInContext('({reserveProjectileDodge,settleProjectileDodge,abandonProjectileDodge,forgetProjectileDodge})',reservation);
 const context=vm.createContext({...effects,...api,world,system,console,tryProjectileDodgeMovement:entity=>move(entity,{random:()=>.75}),projectileDodgeTeleportFeedback(entity,base){entity.dimension.playSound('qa:teleport',base)},Math:Object.assign(Object.create(Math),{random:()=>.75}),now:()=>state.time,invincibleDamageFeedback(){state.invincibleFeedback++},definitelyLethalProvisionalHealth:()=>false,PENDING_METAL_RESCUES:new Map(),ACTIVE_EATS:new Map(),CUISINE_EATS:new Map(),PLATE_EATS:new Map(),PENDING_USES:new Map(),SETTLED:new Map(),VIGOR_LAST:new Map(),SNEAK_LAST:new Map(),NUMB_VISUAL:new Set(),stopSoundHandle(){},forgetEatingItem(){},EAT_PROFILE_PROPERTY:'profile',EAT_HAND_PROPERTY:'hand',EAT_PROJECTION_PROPERTY:'projection',EAT_NATIVE_TICKS_PROPERTY:'native_ticks',EAT_ELAPSED_TICKS_PROPERTY:'elapsed_ticks'});
 vm.runInContext(fx+'\n'+(old?baseline.subscriber:before),context);
 if(!old){for(const line of main.split('\n').filter(x=>x.startsWith('world.afterEvents.')&&(x.includes('forgetProjectileDodge('))))vm.runInContext(line,context);}
 function hit({actor=entity,projectile=true,cancel=false,cause='projectile'}={}){const event={cancel,hurtEntity:actor,damage:1,damageSource:{cause,...(projectile?{damagingProjectile:{id:'arrow'}}:{})}};state.restricted=true;try{hitCallback(event)}finally{state.restricted=false}return event;}
 function flush(delta=1){state.time+=delta;system.currentTick=state.time;while(queue.length)queue.shift()();}
 return {state,entity,wrapper,hit,flush,queue,effects,api,log,remaining:()=>Math.max(0,(JSON.parse(state.raw??'{}').projectile_dodge?.until??state.time)-state.time),setTime:t=>{state.time=t;system.currentTick=t},readFault:f=>readFault=f,clearReadFault:()=>readFault=undefined,fault:f=>writeFault=f,clearFault:()=>writeFault=undefined,writeRaw:r=>state.raw=r,teleportHook:f=>teleportHook=f,scheduleFault:(mode='before')=>scheduleFault=mode,
 refresh:(ticks=remaining)=>vm.runInContext('fxSet',context)(entity,'projectile_dodge',ticks),otherEffect:()=>vm.runInContext('fxSet',context)(entity,'warmth',100),prune:()=>effects.writeEffects(entity,effects.readEffects(entity)),milk:()=>effects.clearEffects(entity,{milk:true}),emit:name=>{for(const f of signals[name]??[])f(name==='leave'?{playerId:entity.id}:name==='spawn'?{player:entity,initialSpawn:true}:name==='death'?{deadEntity:entity}:{removedEntityId:entity.id})}};
}
test('retained actual G84 subscriber demonstrates two protected hits and two teleports from one200 charge',()=>{const f=fixture(200,{old:true});const a=f.hit(),b=f.hit();assert.equal(a.cancel,true);assert.equal(b.cancel,true);assert.equal(f.queue.length,2);f.flush();assert.equal(f.state.teleports,2);assert.equal(f.remaining(),0)});
for(const remaining of [1,100,200,201,400,401,600])test(remaining+' ticks reserve ceil(duration/200) charges before any native write',()=>{const f=fixture(remaining),capacity=Math.ceil(remaining/200),events=Array.from({length:capacity+1},()=>f.hit());assert.deepEqual(events.map(e=>e.cancel),[...Array(capacity).fill(true),false]);assert.equal(f.state.writes,0);assert.equal(f.state.beforeWrites,0);f.flush();assert.equal(f.state.teleports,capacity);assert.equal(f.remaining(),0)});
test('401 permits three callbacks at next tick even when the second native debit removes the effect',()=>{const f=fixture(401);assert.deepEqual(Array.from({length:4},()=>f.hit().cancel),[true,true,true,false]);f.flush();assert.equal(f.state.teleports,3);assert.equal(JSON.parse(f.state.raw??'{}').projectile_dodge,undefined)});
test('one remaining tick keeps its protected claim after owned next-tick expiry pruning without reviving an effect',()=>{const f=fixture(1);assert.equal(f.hit().cancel,true);f.setTime(1001);f.prune();assert.equal(f.state.raw,undefined);f.flush(0);assert.equal(f.state.teleports,1);assert.equal(f.state.raw,undefined)});
test('a longer queue delay preserves a claimed source generation through raw deadline expiry',()=>{const f=fixture(100);assert.equal(f.hit().cancel,true);f.flush(150);assert.equal(f.state.teleports,1);assert.equal(f.state.raw,undefined)});
for(const cleanup of ['milk','leave','spawn','death','remove'])test(cleanup+' invalidates pending claims even if identical effect bytes later return',()=>{const f=fixture(200);f.hit();const original=f.state.raw;if(cleanup==='milk')f.milk();else f.emit(cleanup);f.writeRaw(original);f.flush();assert.equal(f.state.teleports,0);assert.equal(f.remaining(),199)});
test('explicit same-value effect refresh invalidates the old generation and permits its new independent charge',()=>{const f=fixture(200);f.hit();f.refresh(200);assert.equal(f.hit().cancel,true);f.flush();assert.equal(f.state.teleports,1);assert.equal(f.remaining(),0)});
for(const replacement of [{until:1800,amp:0},{until:1200,amp:1}])test('changed until/amp raw replacement cannot be charged by an earlier claim',()=>{const f=fixture(200);f.hit();f.writeRaw(JSON.stringify({projectile_dodge:replacement}));f.flush();assert.equal(f.state.teleports,0);assert.equal(f.remaining(),replacement.until-f.state.time)});
test('same-tick raw clear is seen despite the ordinary effect cache',()=>{const f=fixture(200);f.hit();f.writeRaw(undefined);assert.equal(f.hit().cancel,false);f.flush();assert.equal(f.state.teleports,0)});
test('ordinary no-op/other-effect writes retain the projectile-dodge generation',()=>{const f=fixture(200);f.hit();f.prune();f.otherEffect();f.flush();assert.equal(f.state.teleports,1);assert.equal(f.remaining(),0);assert.ok(JSON.parse(f.state.raw).warmth)});
test('different wrappers of one native actor share the finite charge and exact debit',()=>{const f=fixture(200);assert.equal(f.hit().cancel,true);assert.equal(f.hit({actor:f.wrapper()}).cancel,false);f.flush();assert.equal(f.state.teleports,1);assert.equal(f.remaining(),0)});
for(const field of ['valid','dimensionId','health'])test('invalid/dead/wrong-dimension target '+field+' does not receive stale mutable work',()=>{const f=fixture(200);f.hit();f.state[field]=({valid:false,dimensionId:'minecraft:nether',health:0})[field];f.flush();assert.equal(f.state.teleports,0);assert.equal(f.state.writes,0)});
test('a setter that applies then throws is acknowledged once by readback',()=>{const f=fixture(401);Array.from({length:4},()=>f.hit());f.fault(value=>{f.state.raw=value;throw Error('after-write fault')});f.flush();assert.equal(f.state.teleports,3);assert.equal(f.remaining(),0)});
for(const mode of ['throws','silent-rejection'])test('unacknowledged '+mode+' cost quarantines the old generation instead of free retries',()=>{const f=fixture(200);f.hit();f.fault(()=>{if(mode==='throws')throw Error('before-write fault')});f.flush();assert.equal(f.state.teleports,0);assert.equal(f.hit().cancel,false);f.clearFault();f.refresh(200);assert.equal(f.hit().cancel,true);f.flush();assert.equal(f.state.teleports,1)});
test('setter reentry cannot protect an extra hit before its cost is acknowledged',()=>{const f=fixture(200);f.hit();let reentrant;f.fault(value=>{reentrant=f.hit();f.state.raw=value});f.flush();assert.equal(reentrant.cancel,false);assert.equal(f.state.teleports,1);assert.equal(f.remaining(),0)});
test('debit is detached before teleport reentry, retaining real remaining capacity',()=>{const f=fixture(401);f.hit();let event;f.teleportHook(()=>{if(!event)event=f.hit()});f.flush();assert.equal(event.cancel,true);assert.equal(f.state.teleports,2);assert.equal(f.remaining(),0)});
test('all16 rejected attempts still spend one charge and leave no pending reservation',()=>{const f=fixture(200,{teleportSuccess:false});assert.equal(f.hit().cancel,true);f.flush();assert.equal(f.state.teleports,16);assert.equal(f.remaining(),0);assert.equal(f.hit().cancel,false)});
test('scheduling failure releases bookkeeping and does not cancel native damage',()=>{const f=fixture(200);f.scheduleFault();assert.equal(f.hit().cancel,false);assert.equal(f.state.writes,0);assert.equal(f.state.teleports,0)});
for(const options of [{cancel:true},{projectile:false}])test('pre-canceled/nonprojectile normal control admits no cost or teleport',()=>{const f=fixture(200);f.hit(options);f.flush();assert.equal(f.state.teleports,0);assert.equal(f.state.writes,0)});
test('absent effect allows ordinary projectile damage',()=>{const f=fixture(0);assert.equal(f.hit().cancel,false);f.flush();assert.equal(f.state.writes,0);assert.equal(f.state.teleports,0)});

test('transient reservation read fault does not release a previously protected200-tick charge',()=>{const f=fixture(200);assert.equal(f.hit().cancel,true);f.readFault(()=>{throw Error('transient raw read')});assert.equal(f.hit().cancel,false);f.clearReadFault();assert.equal(f.hit().cancel,false);f.flush();assert.equal(f.state.teleports,1);assert.equal(f.remaining(),0)});
test('transient admission read fault retains all already queued401-tick reservations',()=>{const f=fixture(401);assert.equal(f.hit().cancel,true);f.readFault(()=>{throw Error('transient raw read')});assert.equal(f.hit().cancel,false);f.clearReadFault();assert.deepEqual([f.hit().cancel,f.hit().cancel,f.hit().cancel],[true,true,false]);f.flush();assert.equal(f.state.teleports,3)});

test('transient mutable read fault quarantines an already canceled charge without refunding it',()=>{const f=fixture(200);assert.equal(f.hit().cancel,true);f.readFault(()=>{throw Error('mutable raw read')});f.flush();f.clearReadFault();assert.equal(f.state.teleports,0);assert.equal(f.hit().cancel,false);f.refresh(200);assert.equal(f.hit().cancel,true);f.flush();assert.equal(f.state.teleports,1)});
test('clock rollback before queued admission does not create another200-tick charge',()=>{const f=fixture(200);assert.equal(f.hit().cancel,true);f.setTime(999);assert.equal(f.hit().cancel,false);f.flush(0);assert.equal(f.state.teleports,1);assert.equal(f.state.raw,undefined);assert.equal(f.hit().cancel,false)});
test('clock rollback after a paid400-tick first hit preserves only its actual remaining charge',()=>{const f=fixture(400);assert.equal(f.hit().cancel,true);f.setTime(999);f.flush(0);assert.equal(f.state.teleports,1);assert.deepEqual([f.hit().cancel,f.hit().cancel],[true,false]);f.flush(0);assert.equal(f.state.teleports,2);assert.equal(f.state.raw,undefined)});
test('retired logical deadline never authorizes a new hit when its native raw effect is absent',()=>{const f=fixture(200);f.hit();f.flush();assert.equal(f.state.raw,undefined);f.setTime(999);assert.equal(f.hit().cancel,false);assert.equal(f.state.teleports,1)});
test('a nonfinite mutable clock or health read does not refund an already canceled hit',()=>{for(const field of ['time','health']){const f=fixture(200);f.hit();f.state[field]=NaN;f.flush(0);f.state.time=1001;f.state.health=20;f.setTime(1001);assert.equal(f.state.teleports,0);assert.equal(f.hit().cancel,false)}});
test('a nonfinite admission clock grants no protection and does not discard earlier claims',()=>{const f=fixture(200);f.hit();f.state.time=NaN;assert.equal(f.hit().cancel,false);f.setTime(1000);assert.equal(f.hit().cancel,false);f.flush();assert.equal(f.state.teleports,1)});
test('reentry after native setter mutation still cannot claim unacknowledged protection',()=>{const f=fixture(400);f.hit();let event;f.fault(value=>{f.state.raw=value;event=f.hit()});f.flush();assert.equal(event.cancel,false);assert.equal(f.state.teleports,1);assert.equal(f.remaining(),199)});

for(const method of ['refresh','milk'])test('failed unchanged owned '+method+' does not release earlier protected charges as a new generation',()=>{const f=fixture(200);assert.equal(f.hit().cancel,true);f.fault(()=>{throw Error('unchanged failed mutator')});if(method==='refresh')f.refresh(300);else assert.throws(()=>f.milk());assert.equal(f.hit().cancel,false);f.clearFault();f.flush();assert.equal(f.state.teleports,1);assert.equal(f.remaining(),0)});
test('owned refresh applied then throwing still replaces the generation after actual acknowledgement',()=>{const f=fixture(200);f.hit();f.fault(value=>{f.state.raw=value;throw Error('acknowledged refresh exception')});f.refresh(300);assert.equal(f.hit().cancel,true);f.clearFault();f.flush();assert.equal(f.state.teleports,1);assert.equal(f.remaining(),99)});

test('ordinary next-tick effect read failure is unknown rather than a new absence generation',()=>{const f=fixture(200);assert.equal(f.hit().cancel,true);f.setTime(1001);f.readFault(()=>{throw Error('ordinary effect read fault')});assert.deepEqual(JSON.parse(JSON.stringify(f.effects.readEffects(f.entity))),{});assert.throws(()=>f.prune());f.clearReadFault();assert.equal(f.hit().cancel,false);f.flush(0);assert.equal(f.state.teleports,1);assert.equal(f.remaining(),0)});

test('explicit refresh based on an unknown effect read cannot erase unrelated native stored effects',()=>{const f=fixture(200);f.writeRaw(JSON.stringify({projectile_dodge:{until:1200,amp:0},warmth:{until:1500,amp:0}}));assert.equal(f.hit().cancel,true);f.setTime(1001);f.readFault(()=>{throw Error('unknown producer read')});f.effects.readEffects(f.entity);f.refresh(300);f.clearReadFault();assert.equal(f.hit().cancel,false);f.flush(0);assert.equal(f.state.teleports,1);assert.equal(JSON.parse(f.state.raw).warmth.until,1500)});
test('a lethal provisional before-hurt health value does not prevent a living target reservation',()=>{const f=fixture(200);f.state.health=-1;assert.equal(f.hit().cancel,true);f.state.health=20;f.flush();assert.equal(f.state.teleports,1);assert.equal(f.remaining(),0)});

test('an unavailable real clock never pays with a different system clock or erases other effects',()=>{const f=fixture(200);f.writeRaw(JSON.stringify({projectile_dodge:{until:1200,amp:0},warmth:{until:1500,amp:0}}));f.hit();f.state.clockFailure=true;f.flush();f.state.clockFailure=false;f.setTime(1001);assert.equal(f.state.teleports,0);assert.equal(f.hit().cancel,false);assert.equal(JSON.parse(f.state.raw).projectile_dodge.until,1200);assert.equal(JSON.parse(f.state.raw).warmth.until,1500)});
test('another actor at a later clock cannot discard an unpaid generation and refund it after rollback',()=>{const f=fixture(200);f.hit();f.readFault(()=>{throw Error('cost state unreadable')});f.flush();f.clearReadFault();f.setTime(1250);let otherRaw=JSON.stringify({projectile_dodge:{until:2000,amp:0}});const other={...f.wrapper(),id:'other-native-operation-subject',getDynamicProperty:key=>key===lifecycle.FX_KEY?otherRaw:undefined,setDynamicProperty:(_key,value)=>otherRaw=value};assert.equal(f.hit({actor:other}).cancel,true);f.setTime(1000);assert.equal(f.hit().cancel,false);f.flush(0);assert.equal(f.state.teleports,1);assert.equal(JSON.parse(f.state.raw).projectile_dodge.until,1200)});

test('combinedFX finite dodge charge owns projectile protection before invincible feedback',()=>{const f=fixture(200);f.writeRaw(JSON.stringify({projectile_dodge:{until:1200,amp:0},invincible:{until:2000,amp:0}}));assert.equal(f.hit().cancel,true);assert.equal(f.state.invincibleFeedback,0);f.flush();assert.equal(f.state.teleports,1);assert.equal(f.remaining(),0);assert.equal(JSON.parse(f.state.raw).invincible.until,2000)});
test('combinedFX depleted dodge budget falls through to invincible for the next projectile',()=>{const f=fixture(200);f.writeRaw(JSON.stringify({projectile_dodge:{until:1200,amp:0},invincible:{until:2000,amp:0}}));assert.deepEqual([f.hit().cancel,f.hit().cancel],[true,true]);assert.equal(f.queue.length,1);assert.equal(f.state.invincibleFeedback,1);f.flush();assert.equal(f.state.teleports,1);assert.equal(f.remaining(),0)});
test('combinedFX nonprojectile damage retains invincible without spending dodge',()=>{const f=fixture(200);f.writeRaw(JSON.stringify({projectile_dodge:{until:1200,amp:0},invincible:{until:2000,amp:0}}));assert.equal(f.hit({projectile:false,cause:'entityAttack'}).cancel,true);assert.equal(f.state.invincibleFeedback,1);f.flush();assert.equal(f.state.teleports,0);assert.equal(f.remaining(),199)});
for(const mode of ['before','after'])test('combinedFX schedule '+mode+' failure abandons dodge bookkeeping and uses independent invincible protection',()=>{const f=fixture(200);f.writeRaw(JSON.stringify({projectile_dodge:{until:1200,amp:0},invincible:{until:2000,amp:0}}));f.scheduleFault(mode);assert.equal(f.hit().cancel,true);assert.equal(f.state.invincibleFeedback,1);f.flush();assert.equal(f.state.teleports,0);assert.equal(f.remaining(),199)});
test('combinedFX externally pre-canceled projectile retains its prior priority without reserving a cost',()=>{const f=fixture(200);f.writeRaw(JSON.stringify({projectile_dodge:{until:1200,amp:0},invincible:{until:2000,amp:0}}));assert.equal(f.hit({cancel:true}).cancel,true);assert.equal(f.state.invincibleFeedback,0);f.flush();assert.equal(f.state.teleports,0);assert.equal(f.remaining(),199)});
