import test from 'node:test';import assert from 'node:assert/strict';
import {refreshPlateFood,normalizePlateRows,plateHighestNutritionIndex,plateEatHighest} from '../../projects/grilling/gameplay_core/behavior_pack/scripts/a25_plate_recipe_core.js';
const N='kaleidoscope_grilling:',raw=['minecraft:apple','minecraft:carrot','minecraft:beef'].map(id=>({id,edible:false,nutrition:0,saturation:0})),cooked=raw.map((r,i)=>({...r,id:i===2?'minecraft:cooked_beef':r.id}));
function row(native=false,cook=true){const props={[N+'skewer_ingredients']:JSON.stringify(raw),[N+'secret_cooked']:cook,[N+'secret_cooked_ingredients']:JSON.stringify(cooked)};return {id:N+'secret_skewer',nutrition:1,saturation:0,...(native?{native:{version:1,id:N+'secret_skewer',props}}:{props})}}
for(const native of [false,true])test('old zero-food packed secret ranks by actual cooked nutrition '+native,()=>{const secret=row(native),before=JSON.stringify(secret),rows=[secret,{id:N+'grilled_fish_skewer',nutrition:6,saturation:.6}];assert.equal(refreshPlateFood(secret).nutrition,9);assert.equal(plateHighestNutritionIndex(rows),0);const result=plateEatHighest(rows);assert.equal(result.eaten.id,N+'secret_skewer');assert.equal(result.rows.length,1);assert.equal(JSON.stringify(secret),before)});
test('raw secret uses raw nutritional multiplier rather than cooked cache',()=>{const r=row(false,false);assert.equal(refreshPlateFood(r).nutrition,3)});
test('unrelated fixed skewer values remain untouched',()=>{const r={id:N+'grilled_fish_skewer',nutrition:6,saturation:.6};assert.equal(refreshPlateFood(r),r)});
test('normalization preserves all recorded metadata while repairing cache',()=>{const r=row(true);r.native.props['third:marker']='kept';const out=normalizePlateRows([r])[0];assert.equal(out.nutrition,9);assert.deepEqual(out.native,r.native);assert.equal(out.native.props['third:marker'],'kept')});
test('malformed legacy cache cannot invent or discard its ingredient payload',()=>{const r=row();r.props[N+'skewer_ingredients']='{bad';const out=refreshPlateFood(r);assert.equal(out,r);assert.equal(out.props[N+'skewer_ingredients'],'{bad')});
for(const cooked of [42,'{}','[{"id":"minecraft:apple"}]','[{"id":""},{"id":"minecraft:apple"},{"id":"minecraft:carrot"}]'])test('invalid present cooked cache retains existing ranking '+String(cooked),()=>{const r=row();r.props[N+'secret_cooked_ingredients']=cooked;assert.equal(refreshPlateFood(r),r)});
test('valid empty cooked cache uses raw fallback like runtime reward',()=>{const r=row();r.props[N+'secret_cooked_ingredients']='[]';assert.equal(refreshPlateFood(r).nutrition,6)});
for(const key of ['version','id'])test('unknown native envelope retains existing row '+key,()=>{const r=row(true);r.native[key]=key==='version'?2:'test:other';assert.equal(refreshPlateFood(r),r)});
test('invalid raw identity preserves original payload and cache',()=>{const r=row();r.props[N+'skewer_ingredients']='[{"id":""},{"id":"minecraft:apple"},{"id":"minecraft:carrot"}]';assert.equal(refreshPlateFood(r),r)});
test('array-valued item id is rejected without coercion for raw and cooked caches',()=>{for(const key of ['skewer_ingredients','secret_cooked_ingredients']){const r=row();r.props[N+key]=JSON.stringify([{id:['minecraft:apple']},{id:'minecraft:carrot'},{id:'minecraft:beef'}]);assert.equal(refreshPlateFood(r),r)}});
