/** Executes production client/host callbacks with storage-operation doubles.
 * These are not engine players or native lifecycle/client acceptance. */
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
import * as oil from '../../projects/grilling/gameplay_core/behavior_pack/scripts/host_api/oil_api_core.js';
import * as pot from '../../projects/grilling/gameplay_core/behavior_pack/scripts/a2734_cookery_oil_pot_core.js';
import * as data from '../../projects/grilling/gameplay_core/behavior_pack/scripts/itemDataCore.js';
import * as snapshot from '../../projects/grilling/gameplay_core/behavior_pack/scripts/skewer_item_snapshot.js';
import {brush} from '../../projects/grilling/gameplay_core/behavior_pack/scripts/core_logic.js';
import {commitSteps} from '../../projects/grilling/gameplay_core/behavior_pack/scripts/a277_grill_transaction_core.js';
const base=new URL('../../projects/grilling/gameplay_core/behavior_pack/scripts/',import.meta.url),source=n=>fs.readFileSync(new URL(n,base),'utf8');
const strip=s=>s.replace(/^import\b[\s\S]*?;\s*/gm,'').replace(/\bexport (?=(class|const|function|async))/g,'').replace(/^export \{[^}]*\};/gm,'');
function fixture(hand='main'){
 let scope='grilling',main,off;const callbacks={script:[],leave:[],spawn:[]},events=[],runs=[],timeouts=[],signal=key=>({subscribe:f=>callbacks[key].push({f,scope})});
 class Item{
  constructor(typeId=oil.FILLED_POT,amount=1){Object.assign(this,{typeId,amount,maxAmount:1,nameTag:'original',lore:['custom lore'],props:{host:{kc_oil_count:32}},keepOnDeath:false,lockMode:'none',destroy:[],place:[],damage:0,enchantments:[]});}
  clone(){return Object.assign(new Item(this.typeId,this.amount),structuredClone({...this}));}
  getRawLore(){return structuredClone(this.lore)}setLore(v){this.lore=structuredClone(v)}
  getDynamicProperty(k){if(this.unreadable)throw Error('metadata unavailable');return this.props[scope]?.[k]}getDynamicPropertyIds(){if(this.unreadable)throw Error('metadata unavailable');return Object.keys(this.props[scope]??{})}setDynamicProperty(k,v){this.props[scope]??={};if(v===undefined)delete this.props[scope][k];else this.props[scope][k]=v}
  getCanDestroy(){if(this.unreadable)throw Error('restriction unavailable');return [...this.destroy]}getCanPlaceOn(){return [...this.place]}
  getComponent(id){return id==='minecraft:durability'?{damage:this.damage}:id==='minecraft:enchantable'?{getEnchantments:()=>this.enchantments.map(x=>({type:{id:x.id},level:x.level}))}:undefined}
 }
 const current=()=>hand==='main'?main:off,set=s=>{if(hand==='main')main=s;else off=s};set(new Item());
 const inventory={size:9,getItem:i=>i===owner.selectedSlotIndex?main:undefined,setItem:(_i,s)=>main=s},equipment={getEquipment:()=>off,setEquipment:(_s,v)=>{off=v;return true},getEquipmentSlot:s=>({hasItem:()=>!!(s==='off'?off:main),getItem:()=>s==='off'?off:main,setItem:v=>{if(s==='off')off=v;else main=v}})};
 const owner={id:'storage-owner',isValid:true,selectedSlotIndex:0,dimension:{id:'minecraft:overworld'},location:{x:1,y:65,z:1},getComponent:id=>id==='minecraft:inventory'?{container:inventory}:id==='minecraft:equippable'?equipment:undefined,getGameMode:()=> 'Survival'};
 const ignore={subscribe(){}},world={getAllPlayers:()=>[owner],getDynamicProperty(){},setDynamicProperty(){},afterEvents:{playerSpawn:signal('spawn'),playerPlaceBlock:ignore,playerLeave:signal('leave')},beforeEvents:{playerInteractWithBlock:ignore,playerBreakBlock:ignore,explosion:ignore}};
 const system={currentTick:100,afterEvents:{scriptEventReceive:signal('script')},sendScriptEvent:(id,message)=>events.push({id,message}),run:f=>runs.push(f),runTimeout:(f,t)=>timeouts.push({f,t})};
 const api={...oil,...pot,...data,...snapshot,world,system,ItemStack:Item,EquipmentSlot:{Mainhand:'main',Offhand:'off'},GameMode:{Creative:'Creative'},console:{warn(){}}};
 scope='host';const host=vm.createContext({...api});vm.runInContext(strip(source('host_api/oil_api_host.js')),host);
 scope='grilling';const client=vm.createContext({...api});vm.runInContext(strip(source('a2735_player_io.js')),client);vm.runInContext(strip(source('a2734_cookery_oil_pot_adapter.js')),client);vm.runInContext(strip(source('oil_api_client.js')),client);
 const ensure=vm.runInContext('ensureOilHandPublished',client);let station={phase:0,lit:true},mutations=0;
 // Continuation performs the real oil plan and brush before crediting the store.
 const continueUse=()=>{const p=vm.runInContext('planCookeryOilPotConsumption',client)(current(),1);assert.equal(p.ok,true);const b=brush(station,1,1200);assert.equal(b.ok,true);assert.equal(commitSteps([{apply(){set(p.next)},rollback(){set(p.before)}},{apply(){station=b.state;mutations++},rollback(){station={phase:0,lit:true}}}]).ok,true);};
 const emit=(event,key='script')=>{for(const row of callbacks[key]){scope=row.scope;row.f(event)}scope='grilling'};
 const request=()=>assert.equal(ensure(owner,hand,continueUse),false);
 const publish=()=>{assert.equal(events[0].id,'senluo:oil_snapshot_request');emit(events.shift());assert.equal(oil.readPublicOil(current()).state.count,32)};
 const reply=(mutate)=>{assert.equal(events[0].id,'senluo:oil_snapshot_response');const event=events.shift();if(mutate){const value=JSON.parse(event.message);mutate(value);event.message=JSON.stringify(value)}emit(event)};
 const run=()=>{for(const f of runs.splice(0))f()};
 return {owner,Item,current,set,request,publish,reply,run,timeouts,supersede(){assert.equal(ensure(owner,hand,continueUse),true)},leave:()=>emit({playerId:owner.id},'leave'),spawn:()=>emit({player:owner},'spawn'),other:()=>hand==='main'?off:main,setOther:s=>{if(hand==='main')off=s;else main=s},get mutations(){return mutations},get state(){return station},oilCount:()=>oil.readPublicOil(current()).state?.count};
}
for(const hand of ['main','off'])test(hand+' legitimate host publication preserves metadata and continues once',()=>{const f=fixture(hand);f.current().props.grilling={'qa:identity':'original'};f.current().destroy=['minecraft:stone'];f.request();f.publish();f.reply();f.run();assert.equal(f.mutations,1);assert.equal(f.oilCount(),31);assert.equal(f.current().props.grilling['qa:identity'],'original');assert.deepEqual(f.current().destroy,['minecraft:stone']);f.run();assert.equal(f.mutations,1)});
for(const stage of ['beforeHost','beforeReply','beforeContinue'])for(const hand of ['main','off'])test(hand+' dimension change '+stage+' prevents debit and old-station mutation',()=>{const f=fixture(hand);f.request();if(stage==='beforeHost')f.owner.dimension.id='minecraft:nether';f.publish();if(stage==='beforeReply')f.owner.dimension.id='minecraft:nether';f.reply();if(stage==='beforeContinue')f.owner.dimension.id='minecraft:nether';f.run();assert.equal(f.mutations,0);assert.equal(f.oilCount(),32)});
for(const stage of ['beforeReply','beforeContinue'])for(const field of ['props','keepOnDeath','lockMode','destroy','place','damage','enchantments','nameTag','lore','amount'])test(field+' replacement '+stage+' rejects same-visible or changed stack',()=>{const f=fixture();f.request();f.publish();if(stage==='beforeContinue')f.reply();const s=f.current().clone();const values={props:{host:{kc_oil_count:32},grilling:{'qa:identity':'replacement'}},keepOnDeath:true,lockMode:'slot',destroy:['minecraft:diamond_block'],place:['minecraft:stone'],damage:1,enchantments:[{id:'minecraft:unbreaking',level:1}],nameTag:'replacement',lore:[...s.lore,'changed'],amount:2};s[field]=values[field];f.set(s);if(stage==='beforeReply')f.reply();f.run();assert.equal(f.mutations,0);assert.equal(f.oilCount(),32)});
for(const stage of ['beforeReply','beforeContinue'])test('invalid owner '+stage+' rejects',()=>{const f=fixture();f.request();f.publish();if(stage==='beforeContinue')f.reply();f.owner.isValid=false;if(stage==='beforeReply')f.reply();f.run();assert.equal(f.mutations,0);assert.equal(f.oilCount(),32)});
test('leave removes pending request so a response cannot revive it',()=>{const f=fixture();f.request();f.publish();f.leave();f.reply();f.run();assert.equal(f.mutations,0);assert.equal(f.oilCount(),32)});
test('selected-slot change rejects both main and offhand deferred gestures',()=>{for(const hand of ['main','off']){const f=fixture(hand);f.request();f.publish();f.owner.selectedSlotIndex=1;f.reply();f.run();assert.equal(f.mutations,0)}});
test('unreadable native metadata fails before sending host request',()=>{const f=fixture();f.current().unreadable=true;f.request();assert.equal(f.mutations,0);assert.equal(f.timeouts.some(x=>x.t===60),false,'no new request timer')});
test('60-tick timeout expires once without authorizing late response',()=>{const f=fixture();f.request();f.publish();const timer=f.timeouts.find(x=>x.t===60);assert.ok(timer);timer.f();f.reply();f.run();assert.equal(f.mutations,0);assert.equal(f.oilCount(),32)});

for(const stage of ['beforeReply','beforeContinue'])for(const axis of ['x','y','z'])test(axis+' movement '+stage+' cancels asynchronous gesture without remote mutation',()=>{const f=fixture();f.request();f.publish();if(stage==='beforeContinue')f.reply();f.owner.location[axis]+=axis==='x'?1000:0.01;if(stage==='beforeReply')f.reply();f.run();assert.equal(f.mutations,0);assert.equal(f.oilCount(),32)});
for(const event of ['leave','spawn'])for(const stage of ['beforeReply','beforeContinue'])test(event+' '+stage+' cancels both pending and already queued response',()=>{const f=fixture();f.request();f.publish();if(stage==='beforeContinue')f.reply();f[event]();if(stage==='beforeReply')f.reply();f.run();assert.equal(f.mutations,0);assert.equal(f.oilCount(),32)});
for(const hand of ['main','off'])for(const field of ['props','lockMode','destroy','damage'])test(hand+' deferred oil hand binds other-hand '+field+' metadata',()=>{const f=fixture(hand),other=new f.Item('qa:bucket');other.lore=['bucket'];f.setOther(other);f.request();f.publish();const changed=f.other().clone();changed[field]=({props:{grilling:{identity:'new'}},lockMode:'slot',destroy:['minecraft:diamond_block'],damage:1})[field];f.setOther(changed);f.reply();f.run();assert.equal(f.mutations,0);assert.equal(f.oilCount(),32)});
test('only the requested oil hand may gain a portable oil payload',()=>{const f=fixture(),other=new f.Item();f.setOther(other);f.request();f.publish();const changed=f.other().clone();oil.writePublicOil(changed,{v:1,type:'',count:32,revision:0},{presentation:false});f.setOther(changed);f.reply();f.run();assert.equal(f.mutations,0);assert.equal(f.oilCount(),32)});

for(const stage of ['beforeReply','beforeContinue'])for(const field of ['count','type','revision'])test('published oil '+field+' changes '+stage+' cannot inherit old interaction',()=>{const f=fixture();f.request();f.publish();if(stage==='beforeContinue')f.reply();const old=oil.readPublicOil(f.current()).state;const next={...old,[field]:({count:7,type:'canola',revision:1})[field]};oil.writePublicOil(f.current(),next,{presentation:false});if(stage==='beforeReply')f.reply();f.run();assert.equal(f.mutations,0);assert.equal(f.oilCount(),next.count)});
for(const stage of ['beforeReply','beforeContinue'])test('new synchronous gesture '+stage+' supersedes old pending/queued continuation',()=>{const f=fixture();f.request();f.publish();if(stage==='beforeContinue')f.reply();f.supersede();const before=oil.readPublicOil(f.current()).state;f.set(oil.createPublicOilPot(f.Item,before.type,before.count-1,f.current(),before.revision+1));if(stage==='beforeReply')f.reply();f.run();assert.equal(f.mutations,0);assert.equal(f.oilCount(),31)});
for(const malformed of ['missing','invalid'])test(malformed+' published-oil acknowledgement cancels deferred action while retaining pot',()=>{const f=fixture();f.request();f.publish();f.reply(value=>{if(malformed==='missing')delete value.publishedOil;else value.publishedOil={v:1,type:'canola',count:65,revision:0}});f.run();assert.equal(f.mutations,0);assert.equal(f.oilCount(),32)});

test('offhand fill cannot inherit an identical main bucket from another selected slot',()=>{const f=fixture('off'),bucket=new f.Item('qa:bucket');f.setOther(bucket);f.request();f.publish();f.owner.selectedSlotIndex=1;f.setOther(bucket.clone());f.reply();f.run();assert.equal(f.mutations,0);assert.equal(f.oilCount(),32)});
