/** Executes canonical world-fluid transfers with storage doubles; no engine actors. */
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
import {commitSteps} from '../../projects/grilling/gameplay_core/behavior_pack/scripts/a277_grill_transaction_core.js';
import * as registry from '../../projects/grilling/gameplay_core/behavior_pack/scripts/oil_source_registry_core.js';
const N='kaleidoscope_grilling:';
class Item{constructor(typeId,amount=1){this.typeId=typeId;this.amount=amount}clone(){return new Item(this.typeId,this.amount)}}
function fixture(count=16,creative=false){const dp=new Map(),slots=[new Item('minecraft:bucket',count),undefined],drops=[];let fault;
 const permutation=(id,level=0)=>({type:{id},getState:()=>level});
 const block={x:50,y:80,z:64,location:{x:50,y:80,z:64},typeId:N+'canola_oil',permutation:permutation(N+'canola_oil'),setType(id){this.typeId=id;this.permutation=permutation(id)},setPermutation(p){this.typeId=p.type.id;this.permutation=p}};
 const bag={size:2,getItem:i=>slots[i]?.clone(),setItem(i,v){slots[i]=v?.clone();if(fault?.('slot'+i)){fault=undefined;throw Error('slot fault')}}};
 const dimension={id:'minecraft:overworld',getBlock:()=>block,playSound(){},spawnItem(s){const entity={getComponent:()=>({itemStack:s}),remove(){drops.splice(drops.indexOf(entity),1)}};drops.push(entity);return entity}};block.dimension=dimension;
 const signal={subscribe(){}};const world={getDynamicProperty:k=>dp.get(k),getDynamicPropertyIds:()=>[...dp.keys()],setDynamicProperty(k,v){if(v===undefined)dp.delete(k);else dp.set(k,v);if(fault?.('registry')){fault=undefined;throw Error('registry fault')}},getDimension:()=>dimension,beforeEvents:{playerInteractWithBlock:signal,playerBreakBlock:signal}};
 const context={...registry,posKey:registry.oilPosKey,commitSteps,world,system:{currentTick:100,runInterval(){}},console,ItemStack:Item,BlockPermutation:{resolve:(id,s)=>permutation(id,s[N+'level'])},creative:()=>creative,playerContainer:()=>bag,captureWritableHand(){const before=slots[0]?.clone();return {before,write:s=>bag.setItem(0,s)}},ensureOilHandPublished:()=>true};
 let raw=fs.readFileSync('projects/grilling/gameplay_core/behavior_pack/scripts/a23_oil_world.js','utf8').replace(/^import\b[\s\S]*?;\s*/gm,'').replace(/\bexport /g,'');vm.runInNewContext(raw+'\nthis.api={takeSource,placeFromBucket,registerSource,readReg};',context);
 return {api:context.api,block,dimension,slots,dp,drops,holder:{location:block.location},fail(fn){fault=fn}};
}
for(const count of [1,16])for(const creative of [false,true])test(`source bucket count ${count}, creative ${creative} conserves containers`,()=>{const f=fixture(count,creative);assert(f.api.takeSource(f.holder,f.block,'canola','main'));assert.equal(f.block.typeId,'minecraft:air');assert.equal(f.slots[0].typeId,creative||count>1?'minecraft:bucket':N+'canola_oil_bucket');assert.equal(f.slots[0].amount,creative?count:count>1?count-1:1);assert.equal(f.slots[1]?.typeId,creative||count>1?N+'canola_oil_bucket':undefined)});
test('source output failure restores source and the entire bucket stack',()=>{const f=fixture();f.fail(k=>k==='slot1');assert.equal(f.api.takeSource(f.holder,f.block,'canola','main'),false);assert.equal(f.slots[0].amount,16);assert.equal(f.slots[1],undefined);assert.equal(f.block.typeId,N+'canola_oil')});
test('source registry failure rolls back placement and oil bucket',()=>{const f=fixture(1);f.slots[0]=new Item(N+'canola_oil_bucket');f.block.setType('minecraft:air');f.fail(k=>k==='registry');assert.equal(f.api.placeFromBucket(f.holder,f.dimension,f.block.location,'canola','main'),false);assert.equal(f.block.typeId,'minecraft:air');assert.equal(f.slots[0].typeId,N+'canola_oil_bucket');assert.equal(f.api.readReg().length,0)});
test('different oil and an existing source cannot be overwritten',()=>{const f=fixture(1);f.slots[0]=new Item(N+'secret_chili_oil_bucket');assert.equal(f.api.placeFromBucket(f.holder,f.dimension,f.block.location,'secret_chili','main'),false);assert.equal(f.slots[0].typeId,N+'secret_chili_oil_bucket');f.slots[0]=new Item(N+'canola_oil_bucket');assert.equal(f.api.placeFromBucket(f.holder,f.dimension,f.block.location,'canola','main'),false)});
