#!/usr/bin/env python3
"""Offline selected vanilla identity/fluid-carrier catalog; no host mutation."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FIXTURE = ROOT / 'development/gameplay_core/fixtures/java-projectile-dodge-liquid-160.json'
OUTPUT = ROOT / 'projects/grilling/gameplay_core/behavior_pack/scripts/projectile_dodge_liquid_catalog.js'


def build():
    fixture = json.loads(FIXTURE.read_text())
    registry = fixture['native_registry']
    blocks = registry['block_ids']
    carriers = fixture['source_fluid_carriers']
    if len(blocks) != registry['data_item_count'] or len(set(blocks)) != len(blocks):
        raise ValueError('Selected publisher registry identity list is inconsistent')
    if blocks != sorted(blocks) or any(not isinstance(name, str) or not name.startswith('minecraft:') for name in blocks):
        raise ValueError('Publisher vanilla identities must be sorted exact names')
    carrier_ids = sorted(carriers)
    if not all(name in blocks for name in carrier_ids):
        raise ValueError('Carrier mapping includes an identity outside the selected native registry')
    if any(not row.get('source_verified') for row in carriers.values()):
        raise ValueError('Carrier original fluid-state source proof is incomplete')
    return ('// Selected official Mojang/bedrock-samples ' + registry['revision'] + '.\n'
            '// Generated by tools/build_projectile_dodge_liquid_catalog.py; source scope and\n'
            '// carrier provenance: fixtures/java-projectile-dodge-liquid-160.json.\n'
            'export const PROJECTILE_DODGE_VANILLA_BLOCK_IDS=Object.freeze(' + json.dumps(blocks, separators=(',', ':')) + ');\n'
            'export const PROJECTILE_DODGE_FLUID_CARRIER_IDS=Object.freeze(' + json.dumps(carrier_ids, separators=(',', ':')) + ');\n')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    output = build()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != output:
            raise SystemExit('Selected liquid catalog differs from its reviewed fixture')
        print('Selected liquid catalog matches reviewed source scope')
    else:
        OUTPUT.write_text(output)
        print('Selected liquid catalog written')


if __name__ == '__main__':
    main()
