"""Generate immutable native-food fallback from the checksum-pinned evidence table."""
from pathlib import Path
import argparse,json
ROOT=Path(__file__).resolve().parents[1]
FIXTURE=ROOT/'development/gameplay_core/fixtures/vanilla-food-1.26.50.json'
OUT=ROOT/'projects/grilling/gameplay_core/behavior_pack/scripts/vanilla_food_nutrition.js'
def render():
    fixture=json.loads(FIXTURE.read_text(encoding='utf-8'))
    table={r['id']:{'nutrition':r['nutrition'],'saturation':r['saturationModifier'],'convertTo':r.get('convertTo','')} for r in fixture['foods']}
    for canonical,legacy in fixture.get('nativeAliases',{}).items():table[canonical]=table[legacy]
    return '// Mojang/bedrock-samples '+fixture['commit']+' ('+fixture['sampleVersion']+').\n// Generated by tools/build_vanilla_food_nutrition.py; provenance and native aliases in fixtures/vanilla-food-1.26.50.json.\nexport const VANILLA_FOOD_NUTRITION=Object.freeze('+json.dumps(table,ensure_ascii=False,sort_keys=True,separators=(',',':'))+');\n'
if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');a=p.parse_args();data=render()
    if a.check:assert OUT.read_text(encoding='utf-8')==data,'native food fallback is stale'
    else:OUT.write_text(data,encoding='utf-8')
    print('Pinned vanilla food fallback verified')
