// Generated by tools/build_rack_tool_display.py. Known original-texture rack sprites only.
export const RACK_TOOL_VISUAL_TYPE="kaleidoscope_grilling:rack_tool_visual";
export const RACK_TOOL_MODEL_INDEX=Object.freeze({"kaleidoscope_cookery:iron_kitchen_knife":0,"kaleidoscope_cookery:gold_kitchen_knife":1,"kaleidoscope_cookery:diamond_kitchen_knife":2,"kaleidoscope_cookery:netherite_kitchen_knife":3,"kaleidoscope_cookery:kitchen_shovel":4,"minecraft:flint_and_steel":5});
export function rackToolVisualModel(typeId){return Object.hasOwn(RACK_TOOL_MODEL_INDEX,typeId)?RACK_TOOL_MODEL_INDEX[typeId]:undefined;}
